"""Real Chromium interaction checks against the locally hosted release build."""
import asyncio,json,io,wave,math,struct,hashlib
from pathlib import Path
from playwright.async_api import async_playwright
from browser_support import ROOT as R, REPORT_DIR, SCREENSHOT_DIR, DemoHost, launch_options, ensure_output_dirs
HTML=(R/'demo/VoiceLog_声迹_交互Demo.html').read_text(encoding='utf-8')
results=[];errors=[];console_errors=[];console_warnings=[];requests=[]
async def main():
 ensure_output_dirs();host=DemoHost();host.start()
 async with async_playwright() as p:
  browser=await p.chromium.launch(**launch_options())
  page=await browser.new_page(viewport={'width':390,'height':844},device_scale_factor=2,accept_downloads=True)
  page.set_default_timeout(6000)
  page.on('pageerror',lambda e:errors.append(str(e)+'\n'+(e.stack or '')))
  page.on('console',lambda m:console_errors.append(m.text) if m.type=='error' else (console_warnings.append(m.text) if m.type=='warning' else None))
  page.on('request',lambda req:requests.append(req.url) if req.url.startswith(('http:','https:')) and '127.0.0.1' not in req.url else None)
  await page.add_init_script("localStorage.setItem('voicelog-v11','legacy-demo-data-must-stay-untouched')")
  async def load():
   await page.goto(host.url,wait_until='load');await page.wait_for_timeout(120)
  async def check(name,fn):
   try:
    out=await fn();assert out is not False, str(out);results.append({'name':name,'passed':True,'detail':out if isinstance(out,(str,int,float,dict,list)) else None});print('PASS',name,flush=True)
   except Exception as e:results.append({'name':name,'passed':False,'error':str(e)});print('FAIL',name,str(e)[:350],flush=True)
  async def ev(js):return await page.evaluate(js)
  async def eq(js,expected):
   actual=await ev(js);assert actual==expected,f'{actual!r} != {expected!r}';return {'value':actual}
  async def click(sel):await page.locator(sel).first.click();await page.wait_for_timeout(80)
  async def dispatch(a,d={}):await page.evaluate('([a,d])=>VoiceLogTest.dispatch(a,d)',[a,d]);await page.wait_for_timeout(80)
  async def shot(name):await page.wait_for_timeout(240);await page.evaluate("document.getElementById('toast-root').innerHTML=''");await page.screenshot(path=str(SCREENSHOT_DIR/name))
  async def reset():
   if await ev('VoiceLogTest.state.graphFull'):await dispatch('close-full-graph')
   await dispatch('confirm-reset');await page.wait_for_timeout(60)
  await load()
  font_probe={}
  try:
   cdp=await page.context.new_cdp_session(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');doc=await cdp.send('DOM.getDocument')
   for selector in ['.brand','.date-heading','.inner-title strong','.event-heading strong','.nav-item']:
    node=await cdp.send('DOM.querySelector',{'nodeId':doc['root']['nodeId'],'selector':selector})
    if node.get('nodeId'):font_probe[selector]=(await cdp.send('CSS.getPlatformFontsForNode',{'nodeId':node['nodeId']})).get('fonts',[])
  except Exception as e:font_probe={'probe_error':str(e)}
  await check('Chinese interface text uses real installed system fonts',lambda:async_value(any(f.get('familyName') in ('Microsoft YaHei UI','Microsoft YaHei','PingFang SC','Noto Sans CJK SC') for fs in font_probe.values() if isinstance(fs,list) for f in fs)))
  await check('clean initial state never migrates or reads legacy storage',lambda:ev('localStorage.getItem("voicelog-ui-merge-v1")===null&&localStorage.getItem("voicelog-v11")==="legacy-demo-data-must-stay-untouched"'))
  await check('HTML starts with 4 destinations',lambda:eq('document.querySelectorAll("#nav button").length',4))
  await check('7 scene envelopes first day',lambda:eq('document.querySelectorAll("[data-block]").length',7))
  await check('morning contains three distinct events',lambda:eq('document.querySelectorAll("[data-block=\\"b-am\\"] [data-event]").length',3))
  await check('only one block initially expanded',lambda:eq('document.querySelectorAll(".scene-block.expanded").length',1))
  await check('actual hardware image embedded',lambda:ev('document.querySelector(".device-photo").naturalWidth>0'))
  await shot('01_home_nested.png')
  await check('navigation floats inside the phone on all sides',lambda:ev('(()=>{let n=document.querySelector(".nav").getBoundingClientRect(),p=document.querySelector(".phone").getBoundingClientRect();return n.left>=p.left+8&&n.right<=p.right-8&&n.bottom<=p.bottom-7})()'))
  await page.locator('#content').evaluate('(el)=>{el.style.scrollBehavior="auto";el.scrollTop=el.scrollHeight}');await page.wait_for_timeout(120)
  await check('bottom recap card is fully visible above floating navigation',lambda:ev('(()=>{let c=document.querySelector(".recap-link").getBoundingClientRect(),n=document.querySelector(".nav").getBoundingClientRect();return c.bottom<=n.top-4&&c.top>=document.querySelector(".appheader").getBoundingClientRect().bottom})()'))
  await shot('home-bottom-390.png');await page.locator('#content').evaluate('(el)=>el.scrollTop=0')
  await click('[data-act="toggle-block"][data-id="b-pm"]')
  await check('afternoon combines six events',lambda:eq('document.querySelectorAll("[data-block=\\"b-pm\\"] [data-event]").length',6))
  await check('opening PM collapses AM',lambda:eq('document.querySelectorAll(".scene-block.expanded").length',1))
  await page.locator('[data-block="b-pm"]').scroll_into_view_if_needed();await shot('02_home_afternoon.png')
  await click('[data-act="toggle-block"][data-id="b-pm"]')
  await check('collapse all blocks possible',lambda:eq('document.querySelectorAll(".scene-block.expanded").length',0))
  await dispatch('group-filter',{'filter':'工作'})
  await check('work filter keeps separate contiguous intervals',lambda:eq('document.querySelectorAll("[data-block]").length',2))
  await dispatch('group-filter',{'filter':'全部'});await dispatch('date',{'date':'all'})
  await check('multi-day remains ordered envelopes',lambda:eq('document.querySelectorAll("[data-block]").length',8))
  await shot('03_home_multiday.png')
  await dispatch('date',{'date':'2026-10-16'});await dispatch('block-detail',{'id':'b-am'})
  await check('block route contains all three records',lambda:eq('document.querySelectorAll("[data-event]").length',3))
  await check('local graph instantiated',lambda:ev('!!VoiceLogTest.graph && VoiceLogTest.graph.cy.nodes().length>1'))
  await shot('04_block_detail.png');await dispatch('back')
  await click('[data-mode="people"]')
  await check('vertical people chart exists',lambda:ev('!!VoiceLogTest.people'))
  await check('morning active people ordered left',lambda:eq('VoiceLogTest.people.order.slice(0,2)', ['lin','yuan']))
  await check('09:50 e02 bars match exact shared and short intervals',lambda:ev('(()=>{let p=VoiceLogTest.people,a=document.querySelector(".enc-card[data-person=lin][data-id=e02]"),b=document.querySelector(".enc-card[data-person=yuan][data-id=e02]"),c=document.querySelector(".enc-card[data-person=chen][data-id=e02]");return Math.abs(parseFloat(a.style.height)-55*p.scale)<.1&&Math.abs(parseFloat(b.style.height)-55*p.scale)<.1&&Math.abs(parseFloat(c.style.height)-20*p.scale)<.1})()'))
  await check('people plot is inset from both phone edges',lambda:ev('(()=>{let p=document.querySelector(".phone").getBoundingClientRect(),c=document.querySelector(".people-chart-card").getBoundingClientRect();return c.left>=p.left+12&&c.right<=p.right-12})()'))
  await check('people chart scrolls vertically with no crossing time cursor',lambda:ev('(()=>{let v=document.querySelector("#people-viewport");return v.scrollHeight>v.clientHeight*4&&document.querySelector("#people-now")===null&&getComputedStyle(v).overflowY==="auto"})()'))
  await check('personal context includes e06 and excludes private gaps and night preview',lambda:ev('(()=>{let a=VoiceLogTest.people.selfIntervals();return a.some(x=>x[0]===780&&x[1]===910)&&!a.some(x=>[[720,760],[1080,1105],[1380,1439]].some(y=>x[0]===y[0]&&x[1]===y[1]))})()'))
  await shot('05_people_morning.png')
  await page.locator('[data-act="people-window-menu"]').click();await page.locator('[data-act="people-window-set"][data-start="900"]').click();await ev('VoiceLogTest.people.seek(1010)');await page.wait_for_timeout(330)
  await check('15–17 window includes the judge encounter',lambda:ev('VoiceLogTest.state.peopleWindow.startMinute===900&&VoiceLogTest.people.entries.some(x=>x.episodeId==="e15")'))
  await check('afternoon evaluator moves to first contact lane',lambda:eq('VoiceLogTest.people.order[0]','judge'))
  await check('judge bar keeps its full 25-minute duration across the old window boundary',lambda:ev('(()=>{let e=document.querySelector(".enc-card[data-person=judge][data-id=e15]");return !!e&&Math.abs(parseFloat(e.style.height)-25*VoiceLogTest.people.scale)<.1})()'))
  await check('avatars/lanes positions aligned',lambda:ev("""(()=>{let p=VoiceLogTest.people;return p.order.every(id=>{let h=document.querySelector('[data-person-head="'+id+'"]'),l=document.querySelector('[data-person-lane="'+id+'"]');return h.style.transform===l.style.transform})})()"""))
  await shot('06_people_afternoon.png')
  await page.locator('#people-viewport').evaluate('(el)=>el.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,pointerId:1}))');await ev('VoiceLogTest.people.seek(950)')
  await check('time-column order stays locked during vertical touch',lambda:ev('VoiceLogTest.people.lock&&VoiceLogTest.people.order[0]==="judge"'))
  await page.locator('#people-viewport').evaluate('(el)=>el.dispatchEvent(new PointerEvent("pointercancel",{bubbles:true,pointerId:1}))')
  await check('pointer cancellation releases vertical-scroll order lock',lambda:ev('!VoiceLogTest.people.lock&&VoiceLogTest.people.order[0]==="lin"'))
  await ev('VoiceLogTest.people.selectWindow(900)');await ev('VoiceLogTest.people.seek(1010)');await page.wait_for_timeout(330)
  before_scroll=await ev('document.querySelector("#people-viewport").scrollTop');await page.locator('#people-viewport').evaluate('(el)=>el.scrollTop+=210');await page.wait_for_timeout(200)
  await check('vertical scrolling changes the visible time and focus',lambda:ev(f'document.querySelector("#people-viewport").scrollTop>{before_scroll+170}&&VoiceLogTest.state.focus>1010'))
  await shot('people-scroll-moved-390.png')
  await ev('VoiceLogTest.people.selectWindow(900)');await ev('VoiceLogTest.people.seek(1010)');await page.wait_for_timeout(330)
  await dispatch('people-stable');old=await ev('VoiceLogTest.people.order')
  await ev('VoiceLogTest.people.seek(1020)');await page.wait_for_timeout(310)
  await check('fixed order ignores time ranking',lambda:eq('VoiceLogTest.people.order',old))
  await dispatch('people-stable');await ev('VoiceLogTest.people.seek(1010)');await page.wait_for_timeout(300)
  await click('[data-act="all-people"]');await check('full people list not limited to visible columns',lambda:eq('document.querySelectorAll("[data-person-search]").length',8))
  await page.locator('#people-search').fill('小林');await check('people list search',lambda:eq('document.querySelectorAll("[data-person-search]:not([hidden])").length',1))
  await click('[data-act="people-pin"][data-id="lin"]');await check('pin keeps identity left',lambda:eq('VoiceLogTest.people.order[0]','lin'))
  await dispatch('all-people');await dispatch('people-unpin');await ev('VoiceLogTest.people.seek(1010)');await page.wait_for_timeout(330)
  await page.locator('.enc-card[data-person="judge"]').click();await page.wait_for_timeout(100)
  await check('encounter sheet matches interval',lambda:ev('document.querySelector(".sheet").textContent.includes("评审交流者")'))
  await shot('07_people_encounter.png');await click('[data-act="encounter-person"]')
  await check('person page shows three candidate interpretations',lambda:eq('document.querySelectorAll("[data-candidate]").length',3))
  await click('#appheader [data-act="person-consent"]');await check('person identity settings remain available from the page header',lambda:eq('VoiceLogTest.state.sheet.kind','person-consent'));await click('.sheet-title [data-act="close-sheet"]')
  await shot('08_person_candidates.png');await click('[data-act="select-candidate"][data-id="evidence"]')
  await check('candidate can be explicitly selected',lambda:eq('VoiceLogTest.store.candidateChoices["ci-judge"]','evidence'))
  await page.locator('[data-candidate="winning"] summary').click();await click('[data-act="reject-candidate"][data-id="winning"]');await check('unsupported interpretation can be opened and rejected',lambda:ev('VoiceLogTest.store.rejectedCandidates.includes("ci-judge:winning")'))
  await page.locator('#person-reply-text').fill('我打开原话和另一种解释，请你核对。');await click('[data-act="save-person-reply"]')
  await check('reply saves as draft not sent',lambda:ev('VoiceLogTest.store.notes.some(n=>n.kind==="reply_draft"&&n.personId==="judge")&&VoiceLogTest.store.replyDrafts["ci-judge:evidence"]==="我打开原话和另一种解释，请你核对。"'))
  await check('featured understanding points to the approved exact quote',lambda:ev('document.querySelector(".analysis-quote-card .quote-meta .ref").dataset.id==="r-e15-2"&&document.querySelector(".analysis-quote-card .quote-meta time").textContent==="00:30–00:42"'))
  await click('.analysis-quote-card .quote-meta .ref');await check('quote opens its exact source interval',lambda:ev('VoiceLogTest.state.sheet.kind==="ref"&&document.querySelector(".sheet").textContent.includes("00:30—00:42")'))
  await shot('quote-source-390.png');await click('#overlays [data-act="source-record"]')
  await check('full record highlights the cited segment',lambda:ev('VoiceLogTest.state.route==="episode"&&document.querySelector(".transcript-line.selected")!==null'))
  await page.locator('#appheader [data-act="back"]').click();await check('return from source restores the person tab and selection',lambda:ev('VoiceLogTest.state.route==="person"&&VoiceLogTest.state.personTab==="理解"&&VoiceLogTest.store.candidateChoices["ci-judge"]==="evidence"'))
  await page.locator('#appheader [data-act="back"]').click();await check('return to people restores date, time window and focus',lambda:ev('VoiceLogTest.state.homeMode==="people"&&VoiceLogTest.state.peopleWindow.startMinute===900&&VoiceLogTest.state.focus===1010'))
  await page.reload();await page.wait_for_timeout(250);await check('candidate and reply drafts survive a real browser reload',lambda:ev('VoiceLogTest.store.candidateChoices["ci-judge"]==="evidence"&&VoiceLogTest.store.replyDrafts["ci-judge:evidence"]==="我打开原话和另一种解释，请你核对。"&&localStorage.getItem("voicelog-v11")==="legacy-demo-data-must-stay-untouched"'))
  await dispatch('person',{'id':'judge'})
  await shot('person-after-reload-390.png')
  await dispatch('person-graph');await page.wait_for_timeout(300)
  await check('person-scoped graph excludes unrelated episodes',lambda:ev('VoiceLogTest.graph.g.nodes.filter(n=>n.type==="event").every(n=>n.id==="e15")'))
  await dispatch('close-full-graph');await dispatch('nav',{'route':'home'});await dispatch('open-full-graph',{'scope':'all'});await page.wait_for_timeout(350)
  await check('full graph has actual nodes and edges',lambda:ev('VoiceLogTest.graph.cy.nodes().length>=30&&VoiceLogTest.graph.cy.edges().length>=30'))
  await check('phone graph opens focused and invites touch exploration',lambda:ev('VoiceLogTest.graph.selected===null&&VoiceLogTest.graph.cy.nodes(".dim").length===0&&document.querySelector("#graph-inspector").textContent.includes("拖动图谱")&&VoiceLogTest.graph.cy.zoom()>=.58&&document.querySelector("#graph-overlay").parentElement.id==="phone"'))
  await shot('09_graph_focus.png')
  old_zoom=await ev('VoiceLogTest.graph.cy.zoom()');await click('[data-act="graph-zoom"][data-factor="1.25"]')
  await check('graph zoom control works',lambda:ev(f'VoiceLogTest.graph.cy.zoom()>{old_zoom}'))
  await page.locator('#graph-search').fill('评审');await page.wait_for_timeout(80)
  await check('graph searches nodes',lambda:ev('document.querySelectorAll("#graph-search-results button").length>0'))
  await page.locator('#graph-search-results button').first.click();await page.wait_for_timeout(350)
  await check('search opens exact node detail',lambda:ev('document.querySelector("#graph-inspector").textContent.includes("评审")'))
  # Real canvas click selects; coordinate taken from graph renderer.
  await ev('VoiceLogTest.graph.select("decision",true)');await page.wait_for_timeout(300)
  rp=await ev('VoiceLogTest.graph.cy.getElementById("decision").renderedPosition()');bbox=await page.locator('#full-graph-canvas').bounding_box();await page.mouse.click(bbox['x']+rp['x'],bbox['y']+rp['y']);await page.wait_for_timeout(80)
  await check('canvas node hit selects exact node',lambda:eq('VoiceLogTest.graph.selected','decision'))
  # drag a node, measure graph-space displacement
  oldpos=await ev('VoiceLogTest.graph.cy.getElementById("decision").position()')
  old_graph_positions=await ev('Object.fromEntries(VoiceLogTest.graph.cy.nodes().map(n=>[n.id(),{...n.position()}]))')
  await page.mouse.move(bbox['x']+rp['x'],bbox['y']+rp['y']);await page.mouse.down();await page.mouse.move(bbox['x']+rp['x']+32,bbox['y']+rp['y']-24,steps=12);await page.wait_for_timeout(190)
  linked_js='(()=>{let before='+json.dumps(old_graph_positions)+';let cy=VoiceLogTest.graph.cy,center=cy.getElementById("decision"),neighbors=new Set(center.connectedEdges().connectedNodes().map(n=>n.id()));let moved=cy.nodes().filter(n=>n.id()!=="decision"&&Math.hypot(n.position("x")-before[n.id()].x,n.position("y")-before[n.id()].y)>.5);return moved.length>cy.nodes().length/2&&moved.some(n=>neighbors.has(n.id())&&Math.hypot(n.position("x")-before[n.id()].x,n.position("y")-before[n.id()].y)>3)})()'
  await check('dragging one graph node pulls connected and surrounding nodes',lambda:ev(linked_js));await shot('graph-linked-drag-390.png');await page.mouse.up();await page.wait_for_timeout(260)
  await check('dragging canvas node changes coordinates',lambda:ev(f'Math.hypot(VoiceLogTest.graph.cy.getElementById("decision").position("x")-{oldpos["x"]},VoiceLogTest.graph.cy.getElementById("decision").position("y")-{oldpos["y"]})>15'))
  # Pan on empty canvas lower-left, may clear selection; verifies camera state
  oldpan=await ev('VoiceLogTest.graph.cy.pan()');await page.mouse.move(bbox['x']+30,bbox['y']+180);await page.mouse.down();await page.mouse.move(bbox['x']+80,bbox['y']+220,steps=10);await page.mouse.up();await page.wait_for_timeout(100)
  await check('background drag pans camera',lambda:ev(f'Math.hypot(VoiceLogTest.graph.cy.pan("x")-({oldpan["x"]}),VoiceLogTest.graph.cy.pan("y")-({oldpan["y"]}))>10'))
  await dispatch('graph-select',{'id':'e15'});await page.wait_for_timeout(280)
  count=await ev('VoiceLogTest.graph.cy.nodes().length');await dispatch('graph-expand',{'id':'e15'});await page.wait_for_timeout(600)
  await check('expand adds citation neighbors',lambda:ev(f'VoiceLogTest.graph.cy.nodes().length>{count}'))
  await shot('10_graph_expand.png');await click('#graph-sources');await page.wait_for_timeout(600)
  await check('full evidence view includes every allowed node',lambda:ev('VoiceLogTest.graph.cy.nodes().length===VoiceLogTest.graph.g.nodes.length'))
  await dispatch('graph-fit');await page.wait_for_timeout(300);await shot('11_graph_all.png')
  await dispatch('graph-kind',{'kind':'person'});await page.wait_for_timeout(600)
  await check('people filter retains real encounter edges',lambda:ev('(()=>{let g=VoiceLogTest.graph;return g.cy.nodes().filter(n=>n.data("type")==="person").length>=8&&g.cy.nodes().filter(n=>n.data("type")==="event").length>0&&g.cy.edges().filter(e=>e.data("type")==="participant").length>=10&&g.cy.edges().every(e=>["participant","source"].includes(e.data("type")))&&!g.cy.nodes().filter(n=>n.data("type")==="project").length&&!g.cy.nodes().filter(n=>n.data("type")==="concept").length})()'))
  await check('people filter displays its connecting records',lambda:ev('VoiceLogTest.graph.cy.nodes().filter(n=>n.hasClass("bridge")).length>0&&VoiceLogTest.graph.cy.nodes().filter(n=>n.hasClass("bridge")).every(n=>!!n.style("label"))'))
  await dispatch('graph-kind',{'kind':'concept'});await page.wait_for_timeout(600)
  await check('concept filter keeps actual evidence links',lambda:ev('(()=>{let g=VoiceLogTest.graph;return g.cy.nodes().filter(n=>n.data("type")==="concept").length>0&&g.cy.nodes().filter(n=>n.data("type")==="event").length>0&&g.cy.edges().filter(e=>e.data("type")==="derived").length>0&&!g.cy.nodes().filter(n=>n.data("type")==="project").length})()'))
  await dispatch('graph-kind',{'kind':'all'});await page.wait_for_timeout(500);await dispatch('graph-select',{'id':'e15'});await page.wait_for_timeout(300)
  await page.locator('#graph-inspector [data-act="ref"]').first.click();await page.wait_for_timeout(100)
  await check('source sheet suspends graph',lambda:ev('!VoiceLogTest.state.graphFull&&VoiceLogTest.state.sheet.kind==="ref"'))
  await shot('12_source_drawer.png');await click('.sheet-title [data-act="close-sheet"]');await page.wait_for_timeout(600)
  await check('return from source restores selected graph node',lambda:eq('VoiceLogTest.graph.selected','e15'))
  await click('[data-act="graph-access-list"]');await page.locator('#node-list-search').fill('并集');await page.locator('.graph-list-item:not([hidden])').first.click();await page.wait_for_timeout(600)
  await check('accessible node list navigation',lambda:ev('VoiceLogTest.state.graphFull&&document.querySelector("#graph-inspector").textContent.includes("并集")'))
  await click('#graph-inspector [data-act="graph-ask"]');await check('graph enters scoped chat',lambda:eq('VoiceLogTest.state.route','chat'))
  await check('graph chat keeps recording scope',lambda:eq('VoiceLogTest.state.scope.kind','episode'))
  await check('chat composer stays above the floating navigation',lambda:ev('document.querySelector(".composer").getBoundingClientRect().bottom<=document.querySelector(".nav").getBoundingClientRect().top+1'))
  await click('[data-act="scope"]');await page.locator('#scope-search').fill('上午');await page.locator('.scope-choice:not([hidden])').first.click();await check('block scope can be selected',lambda:eq('VoiceLogTest.state.scope.kind','block'))
  await page.locator('#chat-input').fill('今天的方向有什么变化？');await page.locator('#chat-form button[type="submit"]').click();await page.wait_for_timeout(500)
  await check('chat provides scope-safe citations',lambda:ev('VoiceLogTest.store.messages.at(-1).refs.every(id=>VoiceLogTest.core.resolveRef(VoiceLogTest.data,id,VoiceLogTest.state.scope).ok)'))
  await shot('13_chat_scoped.png')
  await dispatch('set-scope',{'kind':'person','id':'judge'});await page.locator('#chat-input').fill('评审在关心什么？');await page.locator('#chat-form button[type="submit"]').click();await page.wait_for_timeout(500)
  await check('question outside known fixture does not invent sources',lambda:ev('(VoiceLogTest.store.messages.at(-1).refs||[]).every(id=>VoiceLogTest.core.resolveRef(VoiceLogTest.data,id,VoiceLogTest.state.scope).ok)'))
  await dispatch('voice');await dispatch('voice-pause');await check('voice pause',lambda:eq('VoiceLogTest.state.voice','paused'))
  await dispatch('voice-interrupt');await check('voice interruption leaves no open panel',lambda:ev('VoiceLogTest.state.sheet===null'))
  await dispatch('nav',{'route':'scenes'});await check('scene symbols are centered in their tiles',lambda:ev('Array.from(document.querySelectorAll(".scene-list-card .tileicon")).every(t=>{let s=t.querySelector("svg").getBoundingClientRect(),b=t.getBoundingClientRect();return Math.abs((s.left+s.right)/2-(b.left+b.right)/2)<1&&Math.abs((s.top+s.bottom)/2-(b.top+b.bottom)/2)<1})'));await shot('scenes-centered-390.png');await click('[data-act="scene"][data-id="learning"]');await check('scene retains four shared tabs',lambda:eq('document.querySelectorAll(".viewtabs button").length',4))
  await shot('14_scene_learning.png');await dispatch('tab',{'tab':'分析'});await shot('15_learning_analysis.png')
  await dispatch('learning');await page.locator('#interval-range').evaluate('(el)=>{el.value="12";el.dispatchEvent(new Event("input",{bubbles:true}))}');await check('interactive visualization recomputes union',lambda:eq('document.querySelector("#union-total").textContent','22'))
  await click('[data-act="learning-answer"][data-answer="correct"]');await check('learning feedback only after answer',lambda:ev('!!VoiceLogTest.state.learningFeedback'))
  await shot('16_learning_interactive.png');await dispatch('episode',{'id':'e02'});await dispatch('ref',{'id':'r-e02-1'});await dispatch('correct',{'id':'e02','segment':'e02-s1'});await page.locator('#correction-text').fill('首页按连续场景分组，每个场景内部保留几件事。');await click('[data-act="confirm-correction"]')
  await check('correction creates revision and stale original ref',lambda:ev('VoiceLogTest.core.resolveRef(VoiceLogTest.data,"r-e02-1").stale'))
  await check('original quote history retained',lambda:ev('VoiceLogTest.data.episodes.find(e=>e.id==="e02").segments[0].history.length===1'))
  await shot('17_source_revision.png');await dispatch('history',{'id':'e02','segment':'e02-s1'});await click('[data-act="restore-transcript"]');await check('restore makes new revision not overwrite',lambda:eq('VoiceLogTest.data.episodes.find(e=>e.id==="e02").segments[0].revision',3))
  await dispatch('close-sheet');await dispatch('close-sheet');await dispatch('note',{'id':'e02'});await page.locator('#note-text').fill('这是一条本人补充。');await click('[data-act="save-note"]');await check('personal note saved separately',lambda:ev('VoiceLogTest.store.notes.some(n=>n.text==="这是一条本人补充。")'))
  # Bind an explicit synthetic tone as a playback fixture, not as original recorded speech.
  with io.BytesIO() as bio:
   with wave.open(bio,'wb') as w:
    w.setnchannels(1);w.setsampwidth(2);w.setframerate(8000);w.writeframes(b'\0\0'*(8000*42))
   buf=bio.getvalue()
  await dispatch('ref',{'id':'r-e01-1'})
  async with page.expect_file_chooser() as fc:await page.locator('#overlays [data-act="bind-audio"]').click()
  chooser=await fc.value;await chooser.set_files({'name':'定位测试_静音.wav','mimeType':'audio/wav','buffer':buf});await page.wait_for_timeout(350)
  await check('local media loads and seeks cited time',lambda:ev('Math.abs(document.querySelector("#overlays audio").currentTime-10)<.3'))
  await dispatch('source-record',{'id':'e01','segment':'e01-s1'});await page.wait_for_timeout(150)
  await check('source jump highlights exact sentence',lambda:ev('document.querySelector("[data-segment=e01-s1]").classList.contains("selected")'))
  # tiny PNG generated only as test upload, not product image generation
  from PIL import Image
  bio=io.BytesIO();Image.new('RGB',(12,12),(50,80,55)).save(bio,format='PNG')
  async with page.expect_file_chooser() as fc:await click('[data-act="photo"]')
  await (await fc.value).set_files({'name':'测试附件.png','mimeType':'image/png','buffer':bio.getvalue()});await page.wait_for_timeout(200)
  await check('local photo is rendered from saved input',lambda:ev('document.querySelector("img[alt=\\"本人补充照片\\"]").naturalWidth===12'))
  await click('[data-act="remove-photo"]');await check('photo can be removed',lambda:eq('VoiceLogTest.store.photos.length',0))
  await dispatch('sound-detail',{'id':'e02'});await check('sound details route selects sound tab',lambda:eq('VoiceLogTest.state.recordTab','声音'));await shot('18_sound_events.png')
  await reset();await dispatch('calendar')
  await check('calendar cards have no ornamental rail dots',lambda:ev('getComputedStyle(document.querySelector(".plan-card"),"::before").display==="none"&&getComputedStyle(document.querySelector(".calendar-timeline"),"::before").display==="none"&&document.querySelector(".calendar-timeline").getBoundingClientRect().left>=document.querySelector("#content").getBoundingClientRect().left'))
  await check('17 October timed actions sort by time',lambda:eq('Array.from(document.querySelectorAll(".plan-card")).map(x=>x.dataset.action)',['a-sync','a-ceremony']))
  await check('calendar starts with draft status and both unconfirmed actions',lambda:ev('document.querySelectorAll(".plan-card .tag:not(.saved)").length===2&&VoiceLogTest.data.actions.filter(a=>a.date==="2026-10-17"&&a.status==="draft").length===2'))
  await check('16 October no-time task is explicit cross-day todo',lambda:ev('document.querySelector(".fill-card").textContent.includes("10月16日")&&document.querySelector(".fill-card").textContent.includes("发出今晚的新版本")'))
  await check('wish stays in separate note section',lambda:ev('document.querySelector(".wish-note")&&!document.querySelector(".plan-card[data-action=a-wish]")'))
  await click('[data-act="calendar-month-toggle"]');await check('month selector opens a real month grid',lambda:eq('document.querySelectorAll(".month-day").length',42));await click('.month-day[data-date="2026-10-16"]');await check('month selection changes the calendar date',lambda:eq('VoiceLogTest.state.calendarDate','2026-10-16'));await click('.week-day[data-date="2026-10-17"]');await check('week selection returns to 17 October',lambda:eq('VoiceLogTest.state.calendarDate','2026-10-17'))
  await click('[data-act="calendar-filter"][data-filter="pending"]');await check('pending filter shows both draft arrangements',lambda:eq('document.querySelectorAll(".plan-card").length',2));await click('[data-act="calendar-filter"][data-filter="all"]')
  await shot('19_calendar.png');await click('[data-act="save-action"][data-id="a-sync"]');await check('calendar requires an explicit confirmation sheet',lambda:eq('VoiceLogTest.state.sheet.kind','action-confirm'));await shot('calendar-confirm-390.png');await click('[data-act="confirm-action"][data-id="a-sync"]')
  await check('explicit save marks one action locally',lambda:ev('VoiceLogTest.data.actions.find(a=>a.id==="a-sync").status==="saved_demo"&&VoiceLogTest.store.receipts.length===1'))
  await check('new storage key is used without touching legacy demo data',lambda:ev('localStorage.getItem("voicelog-v11")==="legacy-demo-data-must-stay-untouched"&&!!localStorage.getItem("voicelog-ui-merge-v1")'))
  await click('[data-act="calendar-filter"][data-filter="saved"]');await check('saved filter shows only local saved items',lambda:eq('Array.from(document.querySelectorAll(".plan-card")).map(x=>x.dataset.action)',["a-sync"]))
  await click('[data-act="ics-select"]');await check('ICS chooser lists saved event only',lambda:ev('document.querySelectorAll(".ics-choice").length===1&&document.querySelector(".ics-choice").textContent.includes("和小林、阿远联调")'))
  async with page.expect_download() as dl:await click('#overlays [data-act="ics"][data-id="a-sync"]')
  down=await dl.value;ics_path=REPORT_DIR/'test_calendar_export.ics';await down.save_as(ics_path)
  await check('single saved item produces an ICS file',lambda:async_value(down.suggested_filename.lower().endswith('.ics')))
  await check('export preserves explicit event title and UID',lambda:async_value('SUMMARY:和小林、阿远联调' in ics_path.read_text(encoding='utf-8') and 'UID:voicelog-a-sync@local.demo' in ics_path.read_text(encoding='utf-8')))
  await dispatch('close-sheet');await dispatch('calendar-filter',{'filter':'all'});await dispatch('edit-action',{'id':'a-send'});await page.locator('#act-date').fill('2026-10-17');await page.locator('#act-time').fill('09:45');await click('[data-act="update-action"]');await click('[data-act="save-action"][data-id="a-send"]')
  await check('overlapping cross-day task cannot be confirmed',lambda:ev('document.querySelector(".sheet").textContent.includes("时间重叠")&&!document.querySelector(".sheet [data-act=confirm-action]")'))
  await dispatch('close-sheet');await dispatch('cancel-action',{'id':'a-sync'});await check('cancelled action does not return from policy evaluation',lambda:ev('!VoiceLogTest.core.evaluateAction(VoiceLogTest.data.actions.find(a=>a.id==="a-sync"),VoiceLogTest.store.policy,{explicitConfirm:true}).allowed'))
  await dispatch('correct',{'id':'e01','segment':'e01-s1'});await page.locator('#correction-text').fill('这一句的来源修订用于验证日历拦截。');await click('[data-act="confirm-correction"]');await check('editing a cited source marks its draft action stale',lambda:eq('VoiceLogTest.data.actions.find(a=>a.id==="a-ceremony").status','stale'));await dispatch('save-action',{'id':'a-ceremony'});await check('stale source blocks the calendar confirmation button',lambda:ev('document.querySelector(".sheet").textContent.includes("来源版本已变化")&&!document.querySelector(".sheet [data-act=confirm-action]")'));await dispatch('close-sheet')
  await dispatch('mood');await dispatch('mood-edit',{'id':'m2'});await page.locator('#mood-label').fill('其实还有疑问');await page.locator('#mood-note').fill('想等下午再验证。');await click('[data-act="save-mood"]')
  await check('mood corrected by self-report',lambda:eq('VoiceLogTest.store.moodEdits.m2.label','其实还有疑问'));await shot('20_mood.png')
  await dispatch('mood-dismiss',{'id':'m3'});await check('mood candidate dismissed',lambda:ev('VoiceLogTest.store.dismissedMoods.includes("m3")'))
  await dispatch('record');await dispatch('mark-record');await check('record mark state real mock',lambda:eq('VoiceLogTest.state.recordMarks.length',1));await dispatch('pause-record');await check('record pause state',lambda:eq('VoiceLogTest.state.record','paused'));await dispatch('pause-record');await page.locator('#record-note').fill('下一轮检查多人轨道切换。');await shot('21_record_control.png');await dispatch('stop-record');await page.wait_for_timeout(600)
  await check('record mock saves note without synthetic transcript',lambda:ev('VoiceLogTest.data.episodes.at(-1).segments.length===0&&VoiceLogTest.data.episodes.at(-1).source==="manual_note"'))
  await check('new manual note grouped in time envelope',lambda:ev('VoiceLogTest.data.blocks.some(b=>b.id.startsWith("b-notes-")&&b.events.length===1)'))
  await dispatch('device');await dispatch('disconnect');await check('disconnect state explicit',lambda:eq('VoiceLogTest.state.connected',False));await shot('22_device.png');await dispatch('record');await check('cannot start recording while disconnected',lambda:eq('VoiceLogTest.state.record','idle'));await dispatch('close-sheet');await dispatch('disconnect')
  await dispatch('sleep');await check('night only preview and no fake metrics',lambda:ev('document.querySelector("#content").textContent.includes("尚未接入睡眠分析")'));await shot('23_sleep_preview.png')
  await dispatch('recap');await shot('24_recap.png');await dispatch('date',{'date':'2026-10-17'});await dispatch('recap');await check('second-day recap does not show first-day decision as today',lambda:ev('!document.querySelector("#content").textContent.includes("上午，把主线")'))
  await dispatch('search');await page.locator('#search-input').fill('原话');await check('search works with input',lambda:ev('document.querySelectorAll("#content .rowlink").length>0'))
  await reset();await dispatch('episode',{'id':'e15'});await dispatch('delete-record',{'id':'e15'});await click('[data-act="confirm-delete-record"]');await check('deleted evidence not resolvable',lambda:ev('!VoiceLogTest.core.resolveRef(VoiceLogTest.data,"r-e15-1").ok'))
  await dispatch('open-full-graph',{'scope':'all'});await check('deleted event absent in graph',lambda:ev('!VoiceLogTest.graph.g.nodes.some(n=>n.episodeId==="e15")'));await dispatch('close-full-graph');await reset()
  await dispatch('nav',{'route':'scenes'});await page.locator('#content').evaluate('(el)=>el.scrollTop=el.scrollHeight');await dispatch('nav',{'route':'me'})
  await check('me page starts below header after another route was scrolled',lambda:ev('document.querySelector(".person-hero").getBoundingClientRect().top>=document.querySelector(".appheader").getBoundingClientRect().bottom'))
  await check('recording pod precedes appearance setting in me list',lambda:eq('Array.from(document.querySelectorAll("#content .rowlink[data-act]")).map(x=>x.dataset.act).filter(x=>["device","appearance"].includes(x))',["device","appearance"]))
  await shot('me-device-first-390.png');await click('#content [data-act="appearance"]');await shot('appearance-390.png')
  await check('glass setting opens with default level and offline refraction map',lambda:ev('VoiceLogTest.state.route==="appearance"&&document.querySelector("#glass-range").value==="65"&&!!document.querySelector("#voicelog-nav-refraction feImage").getAttribute("href")'))
  await page.locator('#glass-range').evaluate('(el)=>{el.value="90";el.dispatchEvent(new Event("input",{bubbles:true}));el.dispatchEvent(new Event("change",{bubbles:true}))}')
  await check('glass setting changes nav lens scale live',lambda:ev('document.querySelector("#glass-value").textContent==="90%"&&Number(document.querySelector("#voicelog-nav-refraction feDisplacementMap").getAttribute("scale"))<-30'))
  await page.reload();await page.wait_for_timeout(200)
  await check('glass level survives reload in new key',lambda:ev('VoiceLogTest.store.glassLevel===90&&getComputedStyle(document.documentElement).getPropertyValue("--liquid-tint").trim()==="0.543"&&localStorage.getItem("voicelog-v11")==="legacy-demo-data-must-stay-untouched"'))
  await reset()
  # Multi-width layout checks. This tests DOM bounds, not unbounded semantic correctness.
  for w,h in [(320,740),(360,800),(390,844),(430,932)]:
   await page.set_viewport_size({'width':w,'height':h});await dispatch('nav',{'route':'home'})
   await check(f'{w}px document has no horizontal overflow',lambda:ev('document.documentElement.scrollWidth<=innerWidth+1'))
   for route in ['home','scenes','calendar','recap','me','mood','privacy']:
    await dispatch('nav',{'route':route});await check(f'{w}px {route} content no horizontal overflow',lambda:ev('document.querySelector("#content").scrollWidth<=document.querySelector("#content").clientWidth+1'))
   await dispatch('nav',{'route':'home'});await dispatch('home-mode',{'mode':'people'});await ev('VoiceLogTest.people.seek(1020)');await page.wait_for_timeout(300)
   await check(f'{w}px people columns keep every head on its own identity lane',lambda:ev('document.querySelectorAll(".person-head:not(.me-head):not(.inactive)").length===(innerWidth<375?2:3)&&VoiceLogTest.people.order.every(id=>{let h=document.querySelector("[data-person-head="+id+"]"),l=document.querySelector("[data-person-lane="+id+"]");return !!h&&!!l&&h.style.transform===l.style.transform})'))
   await check(f'{w}px people controls inside viewport',lambda:ev('document.querySelector(".people-window-toolbar").scrollWidth<=document.querySelector(".people-window-toolbar").clientWidth+1&&document.querySelector(".people-chart-card").scrollWidth<=document.querySelector(".people-chart-card").clientWidth+1'))
   await shot(f'25_people_{w}.png')
   await dispatch('person',{'id':'judge'});await page.wait_for_timeout(80);await check(f'{w}px understanding text fits the person page',lambda:ev('document.querySelector("#content").scrollWidth<=document.querySelector("#content").clientWidth+1'));await shot(f'{w}_person.png')
   await dispatch('ref',{'id':'r-e15-2'});await page.wait_for_timeout(240);await check(f'{w}px quote sheet stays inside the screen',lambda:ev('document.querySelector(".sheet").getBoundingClientRect().right<=innerWidth+1'));await shot(f'{w}_quote-sheet.png');await dispatch('close-sheet')
   await dispatch('nav',{'route':'calendar'});await check(f'{w}px calendar content fits its viewport',lambda:ev('document.querySelector("#content").scrollWidth<=document.querySelector("#content").clientWidth+1'));await shot(f'{w}_calendar.png')
   await dispatch('nav',{'route':'home'});await dispatch('home-mode',{'mode':'time'});await shot(f'26_home_{w}.png')
   await dispatch('open-full-graph',{'scope':'all'});await page.wait_for_timeout(350);await check(f'{w}px graph dialog inside viewport',lambda:ev('document.querySelector(".graph-fullscreen").scrollWidth<=innerWidth+1'));await dispatch('close-full-graph')
  await page.set_viewport_size({'width':360,'height':800});await dispatch('nav',{'route':'home'});await dispatch('home-mode',{'mode':'people'});await page.wait_for_timeout(200)
  small_order=await ev('VoiceLogTest.people.order.slice(0,2)')
  await page.set_viewport_size({'width':390,'height':844});await page.wait_for_timeout(250)
  identity_js="(()=>{let expected="+json.dumps(small_order,ensure_ascii=False)+";return document.querySelectorAll('.person-head:not(.me-head):not(.inactive)').length===3&&VoiceLogTest.people.order.slice(0,2).every((id,i)=>id===expected[i]&&document.querySelector('[data-person-head=\"'+id+'\"]').style.transform===document.querySelector('[data-person-lane=\"'+id+'\"]').style.transform)})()"
  await check('crossing the 375px breakpoint reveals one extra aligned identity',lambda:ev(identity_js))
  # Simulate 200% browser zoom reflow: 320 physical pixels at DPR 2 yields 160 CSS pixels.
  await page.set_viewport_size({'width':160,'height':740});await dispatch('nav',{'route':'home'})
  await check('200% zoom home fits 160 CSS pixels without horizontal overflow',lambda:ev('document.documentElement.scrollWidth<=innerWidth+1&&document.querySelector("#content").scrollWidth<=document.querySelector("#content").clientWidth+1'))
  await shot('zoom-200-home.png')
  await dispatch('person',{'id':'judge'})
  await check('200% zoom person view fits 160 CSS pixels',lambda:ev('document.querySelector("#content").scrollWidth<=document.querySelector("#content").clientWidth+1'))
  await shot('zoom-200-person.png')
  await dispatch('ref',{'id':'r-e15-2'});await page.wait_for_timeout(240)
  await check('200% zoom quote sheet stays inside the screen',lambda:ev('document.querySelector(".sheet").getBoundingClientRect().right<=innerWidth+1'))
  await shot('zoom-200-quote.png');await dispatch('close-sheet')
  await dispatch('nav',{'route':'calendar'})
  await check('200% zoom calendar fits 160 CSS pixels without horizontal overflow',lambda:ev('document.querySelector("#content").scrollWidth<=document.querySelector("#content").clientWidth+1'))
  await shot('zoom-200-calendar.png')
  # Long names and large text, functional pin labels truncate only inside their own cards.
  await page.set_viewport_size({'width':320,'height':740});await ev('VoiceLogTest.data.persons.find(p=>p.id==="judge").name="参与本次评审交流的超长显示名称"');await dispatch('nav',{'route':'home'});await dispatch('home-mode',{'mode':'people'});await ev('VoiceLogTest.people.seek(1020)');await page.wait_for_timeout(400)
  await check('long person name does not change lane width',lambda:ev('document.querySelector("[data-person-head=judge]").offsetWidth<=120'))
  await shot('27_long_name_320.png');await dispatch('nav',{'route':'home'});await page.add_style_tag(content='body{font-size:20px}.inner-title strong{font-size:17px}.block-title strong{font-size:22px}.pill{font-size:15px}')
  await check('larger content typography still fits width',lambda:ev('document.querySelector("#content").scrollWidth<=document.querySelector("#content").clientWidth+1'));await shot('28_larger_type.png')
  await page.emulate_media(reduced_motion='reduce');await dispatch('home-mode',{'mode':'people'});before=await ev('VoiceLogTest.people.order');await ev('VoiceLogTest.people.seek(570)');await page.wait_for_timeout(60)
  await check('reduced motion keeps lane ordering',lambda:eq('VoiceLogTest.people.order',before))
  # Focus trap / ESC
  await dispatch('about');await page.keyboard.press('Escape');await check('Escape dismisses modal',lambda:ev('!VoiceLogTest.state.sheet'))
  await check('keyboard nav still reachable after dialog',lambda:ev('!document.querySelector("#content").inert'))
  await check('browser runtime has no exceptions',lambda:async_value(len(errors)==0))
  await check('offline release makes zero remote requests',lambda:async_value(len(requests)==0))
  # Fresh desktop render
  await page.close();page=await browser.new_page(viewport={'width':1440,'height':960},device_scale_factor=1);await page.add_init_script("localStorage.setItem('voicelog-v11','legacy-demo-data-must-stay-untouched')")
  await page.goto(host.url,wait_until='load');await page.wait_for_timeout(200);await shot('29_desktop.png')
  await check('desktop judge guide exposes fifteen feature destinations',lambda:ev('document.querySelectorAll(".desktop-guide-item").length===15&&document.querySelector(".desktop-guide-nav").textContent.includes("原话与来源")&&document.querySelector(".desktop-guide-nav").textContent.includes("日历与提醒")&&document.querySelector(".desktop-guide-nav").textContent.includes("记录与隐私")'))
  await page.locator('.desktop-guide-item[data-act="desktop-people"]').click();await check('desktop guide opens people intersection',lambda:ev('VoiceLogTest.state.route==="home"&&VoiceLogTest.state.homeMode==="people"'))
  await page.locator('.desktop-guide-item[data-act="person"]').click();await check('desktop guide opens conversation understanding',lambda:ev('VoiceLogTest.state.route==="person"&&VoiceLogTest.state.person==="lin"'))
  await page.locator('.desktop-guide-item[data-act="ref"]').click();await check('desktop guide opens cited original words',lambda:ev('VoiceLogTest.state.sheet?.kind==="ref"&&document.querySelector(".sheet").textContent.includes("人物交汇")'))
  await dispatch('close-sheet')
  await page.locator('.desktop-guide-item[data-act="calendar"]').click();await check('desktop guide opens calendar',lambda:eq('VoiceLogTest.state.route','calendar'))
  await page.locator('.desktop-guide-item[data-act="device"]').click();await check('desktop guide opens recording device',lambda:eq('VoiceLogTest.state.route','device'))
  await page.locator('.desktop-guide-item[data-act="recap"]').click();await check('desktop guide opens daily recap',lambda:eq('VoiceLogTest.state.route','recap'))
  await page.locator('.desktop-guide-item[data-act="privacy"]').click();await check('desktop guide reaches privacy controls',lambda:eq('VoiceLogTest.state.route','privacy'))
  await check('desktop guide scrolls independently of the phone',lambda:ev('document.querySelector(".desktop-note").scrollHeight>document.querySelector(".desktop-note").clientHeight'))
  await page.locator('.desktop-guide-item[data-act="nav"][data-route="home"]').click();await check('desktop guide returns to timeline',lambda:eq('VoiceLogTest.state.route','home'))
  await page.locator('.desktop-guide-item[data-act="nav"][data-route="scenes"]').click();await check('desktop guide opens scenes',lambda:eq('VoiceLogTest.state.route','scenes'))
  await page.locator('.desktop-guide-item[data-act="nav"][data-route="chat"]').click();await check('desktop guide opens cited conversation',lambda:eq('VoiceLogTest.state.route','chat'))
  await page.locator('.desktop-guide-item[data-act="appearance"]').click();await check('desktop guide opens glass settings',lambda:eq('VoiceLogTest.state.route','appearance'))
  await page.locator('.desktop-guide-item[data-act="learning"]').click();await check('desktop guide opens interval explanation',lambda:eq('VoiceLogTest.state.route','learning'))
  await page.locator('.desktop-guide-item[data-act="mood"]').click();await check('desktop guide opens mood history',lambda:eq('VoiceLogTest.state.route','mood'))
  await page.locator('.desktop-guide-item[data-act="sleep"]').click();await check('desktop guide opens night preview',lambda:eq('VoiceLogTest.state.route','sleep'))
  await page.locator('.desktop-guide-item[data-act="open-full-graph"]').click();await page.wait_for_timeout(350)
  await check('desktop graph remains inside the phone frame',lambda:ev('(()=>{let p=document.querySelector("#phone").getBoundingClientRect(),g=document.querySelector(".graph-fullscreen").getBoundingClientRect();return g.left>=p.left&&g.right<=p.right&&g.top>=p.top&&g.bottom<=p.bottom&&g.width<500&&VoiceLogTest.graph.cy.zoom()>=.58})()'))
  await shot('30_graph_desktop.png')
  await dispatch('graph-kind',{'kind':'person'});await page.wait_for_timeout(550)
  await check('desktop people filter shows connected relationships',lambda:ev('VoiceLogTest.graph.cy.edges().filter(e=>e.data("type")==="participant").length>=10&&VoiceLogTest.graph.cy.nodes().filter(n=>n.data("type")==="event").length>0'))
  await shot('graph-people-connected-desktop.png')
  blocked_page=await browser.new_page(viewport={'width':390,'height':844});blocked_page.on('pageerror',lambda e:errors.append(str(e)+'\n'+(e.stack or '')));blocked_page.on('request',lambda req:requests.append(req.url) if req.url.startswith(('http:','https:')) and '127.0.0.1' not in req.url else None)
  await blocked_page.add_init_script("Object.defineProperty(window,'localStorage',{configurable:false,get(){throw new DOMException('Blocked','SecurityError')}})");await blocked_page.goto(host.url,wait_until='load');await blocked_page.wait_for_timeout(120);page=blocked_page
  await check('app still opens when browser storage permission is denied',lambda:ev('VoiceLogTest.state.route==="home"&&document.querySelector("#content").textContent.includes("上午 · 项目推进")'))
  await dispatch('person',{'id':'judge'});await dispatch('select-candidate',{'analysis':'ci-judge','id':'simple'});await check('storage denial explains the unsaved session without breaking UI',lambda:ev('VoiceLogTest.state.route==="person"&&document.querySelector("#toast-root").textContent.includes("浏览器未允许保存")'))
  await check('storage-denied page also completes without runtime errors',lambda:async_value(len(errors)==0))
  await browser.close()
 host.close()
 report={'mode':'Chromium localhost with actual browser localStorage','browser_version':browser.version,'passed':sum(x['passed'] for x in results),'failed':sum(not x['passed'] for x in results),'checks':results,'page_errors':errors,'console_errors':console_errors,'console_warnings':console_warnings,'external_requests':requests,'system_fonts':font_probe,'html_sha256':hashlib.sha256(HTML.encode()).hexdigest(),'limitations':'Chromium viewport simulation; no physical device, Safari, live recording hardware, ASR, or external calendar.'}
 (REPORT_DIR/'font_rendering.json').write_text(json.dumps({'browser_version':browser.version,'mode':'Chrome DevTools CSS.getPlatformFontsForNode','nodes':font_probe},ensure_ascii=False,indent=2))
 (REPORT_DIR/'browser_checks.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print('BROWSER',report['passed'],'passed;',report['failed'],'failed; errors',errors)
async def async_value(x):return x
asyncio.run(main())
