/* Deterministic unit and property checks on synthetic fixtures only. No ASR/model evaluation. */
'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),C=require('../src/core.js');
const original=JSON.parse(fs.readFileSync(path.join(root,'data/fixture.json'),'utf8'));
const copy=()=>structuredClone(original),out=[];
function test(name,fn){try{let detail=fn();out.push({name,passed:true,detail:detail??null});console.log('PASS',name)}catch(e){out.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message)}}
const ok=assert.ok,eq=assert.deepEqual;
test('brand and version',()=>{eq(original.brand,'VoiceLog / 声迹');eq(original.version,'1.1.0')});
test('episode and block IDs unique',()=>{eq(new Set(original.episodes.map(x=>x.id)).size,16);eq(new Set(original.blocks.map(x=>x.id)).size,8)});
test('all episodes belong to exactly one outer interval',()=>{let counts={};for(const b of original.blocks)for(const id of b.events)counts[id]=(counts[id]||0)+1;for(const e of original.episodes)eq(counts[e.id],1)});
test('nested events remain inside their outer time window',()=>{for(const b of original.blocks){const s=C.ms(`${b.date}T${b.start}:00+08:00`),t=C.ms(`${b.date}T${b.end}:00+08:00`);for(const id of b.events){const e=original.episodes.find(e=>e.id===id);ok(C.ms(e.start)>=s&&C.ms(e.end)<=t,id)}}});
test('day blocks remain chronological and nonoverlapping',()=>{for(const day of original.dates){let b=C.sceneBlocks(original,day);for(let i=1;i<b.length;i++)ok(b[i-1].end<=b[i].start)}});
test('morning has three events and afternoon has six',()=>{eq(C.sceneBlocks(original,'2026-10-16').find(b=>b.id==='b-am').items.length,3);eq(C.sceneBlocks(original,'2026-10-16').find(b=>b.id==='b-pm').items.length,6)});
test('work filtering does not merge separate times',()=>eq(C.sceneBlocks(original,'2026-10-16','工作').map(b=>b.id),['b-am','b-pm']));
test('multi-day includes next-day work, in order',()=>{let bs=C.sceneBlocks(original,'all');eq(bs.length,8);eq(bs[7].id,'b-day2')});
test('deleted episodes disappear from block view',()=>{let d=copy();d.episodes.find(e=>e.id==='e03').deleted=true;eq(C.sceneBlocks(d,'2026-10-16').find(b=>b.id==='b-am').items.length,2)});
test('empty block disappears after its only event is deleted',()=>{let d=copy();d.episodes.find(e=>e.id==='e01').deleted=true;eq(C.sceneBlocks(d,'2026-10-16').length,6)});
test('sleep preview contains no source recording',()=>{let e=original.episodes.find(e=>e.id==='e11');eq(e.status,'preview');eq(e.segments.length,0);eq(original.refs.filter(r=>r.recordingId===e.id).length,0)});
test('private rest does not create audio or graph evidence',()=>{for(const e of original.episodes.filter(e=>!e.public)){eq(e.segments.length,0);eq(original.refs.filter(r=>r.recordingId===e.id).length,0)}});
test('interval union known overlap',()=>eq(C.unionIntervals([[0,20],[10,30],[30,40],[50,60]]),[[0,40],[50,60]]));
test('invalid and reversed intervals excluded',()=>eq(C.unionIntervals([[5,5],[10,3],[NaN,3],[0,4]]),[[0,4]]));
test('window clips intervals',()=>eq(C.unionIntervals([[-10,3],[5,20]],[0,12]),[[0,3],[5,12]]));
test('people plot maps exact minutes to proportional pixel positions',()=>{eq(C.windowY(590,540,660,264),110);eq(C.windowY(540,540,660,264),0);eq(C.windowY(660,540,660,264),264)});
test('people track uses exact clipped interval height with no minimum stretch',()=>{let [a,b]=C.windowRange([[550,555],[555,575],[530,545],[655,670]],540,660,264);eq([a.start,a.end,a.top,a.height],[540,545,0,11]);eq([b.start,b.end,b.top,b.height],[550,575,22,55]);eq(C.windowRange([[550,550]],540,660,264),[]);eq(C.windowRange([[550,570]],600,540,264),[])});
test('same interval scales linearly when the plot height changes',()=>{let a=C.windowRange([[590,610]],540,660,264)[0],b=C.windowRange([[590,610]],540,660,528)[0];eq([a.top*2,a.height*2],[b.top,b.height])});
test('short encounter geometry remains minute-proportional',()=>{let ten=C.windowRange([[590,600]],540,660,264)[0],twenty=C.windowRange([[590,610]],540,660,264)[0];eq(twenty.height,ten.height*2)});
test('randomized interval union matches independent integer bitmap oracle (500 cases)',()=>{let seed=77831;const rnd=n=>{seed=(seed*1664525+1013904223)>>>0;return seed%n};for(let k=0;k<500;k++){let a=Array.from({length:3+rnd(20)},()=>{let x=rnd(120),y=rnd(120);return [x,y]});let mask=Array(120).fill(false);for(const [s,e] of a)if(e>s)for(let x=s;x<e;x++)mask[x]=true;const actual=C.unionIntervals(a).reduce((sum,[s,e])=>sum+e-s,0);eq(actual,mask.filter(Boolean).length)}return {cases:500,seed:77831}});
test('union invariant to input order and duplication',()=>{let spans=original.encounters.map(x=>[x.start,x.end]);eq(C.unionIntervals(spans),C.unionIntervals([...spans].reverse().concat(spans)))});
test('Xiaolin union is 110 minutes, raw sum 117',()=>{let spans=original.encounters.filter(e=>e.personId==='lin'&&e.start.startsWith('2026-10-16'));eq(C.durationMinutes(spans),110);eq(spans.reduce((s,e)=>s+(C.ms(e.end)-C.ms(e.start))/60000,0),117)});
test('unknown/anonymous identity excluded from confirmed-person durations',()=>{for(const p of C.peopleStats(original,'all'))eq(p.consent,'confirmed_demo')});
test('day selector does not count next-day encounters',()=>{let p=C.peopleStats(original,'2026-10-16');eq(p.find(x=>x.id==='lin').minutes,110)});
test('deleted encounter source removed from duration',()=>{let d=copy(),a=C.peopleStats(d,'2026-10-16').find(x=>x.id==='lin').minutes;d.episodes.find(e=>e.id==='e08').deleted=true;ok(C.peopleStats(d,'2026-10-16').find(x=>x.id==='lin').minutes<a)});
test('preview not included as observed daytime episode',()=>eq(C.dayStats(original,'2026-10-16').episodes,13));
test('day counts refer to selected range',()=>{eq(C.dayStats(original,'all').days,2);eq(C.dayStats(original,'2026-10-17').episodes,2)});
test('current people rank before inactive people',()=>eq(C.peopleOrder(original,'2026-10-16',1020)[0],'judge'));
test('stable ordering remains stable across times',()=>{let a=C.peopleOrder(original,'2026-10-16',570);eq(C.peopleOrder(original,'2026-10-16',1020,a,true),a)});
test('pin takes priority without duplicating IDs',()=>{let a=C.peopleOrder(original,'2026-10-16',1020,[],false,'lin');eq(a[0],'lin');eq(new Set(a).size,a.length)});
test('same relevance preserves previous order',()=>{let a=C.peopleOrder(original,'2026-10-16',570);let tail=a.filter(x=>!['lin','yuan','chen'].includes(x));let reversed=[...tail.reverse(),'chen','yuan','lin'];let b=C.peopleOrder(original,'2026-10-16',600,reversed);eq(b.filter(x=>['lin','yuan','chen'].includes(x)),['chen','yuan','lin'])});
test('all source references resolve',()=>{for(const r of original.refs)ok(C.resolveRef(original,r.id).ok,r.id)});
test('every summary item has explicit source mapping',()=>{for(const e of original.episodes.filter(e=>e.source==='audio_fixture')){eq(e.itemRefs.length,e.items.length,e.id);for(const ids of e.itemRefs){ok(ids.length>0);for(const id of ids)ok(C.resolveRef(original,id,{kind:'episode',id:e.id}).ok)}}});
test('references point inside the exact segment',()=>{for(const r of original.refs){let v=C.resolveRef(original,r.id);ok(r.locator.start_ms>=v.segment.start_ms&&r.locator.end_ms<=v.segment.end_ms)}});
test('unknown ref rejected',()=>ok(!C.resolveRef(original,'absent').ok));
test('wrong record scope rejected',()=>ok(!C.resolveRef(original,'r-e01-1',{kind:'episode',id:'e02'}).ok));
test('wrong block scope rejected',()=>ok(!C.resolveRef(original,'r-e01-1',{kind:'block',id:'b-am'}).ok));
test('matching block scope accepted',()=>ok(C.resolveRef(original,'r-e03-1',{kind:'block',id:'b-am'}).ok));
test('wrong date scope rejected',()=>ok(!C.resolveRef(original,'r-e03-1',{kind:'date',id:'2026-10-17'}).ok));
test('wrong person scope rejected',()=>ok(!C.resolveRef(original,'r-e03-1',{kind:'person',id:'lin'}).ok));
test('removed source is unavailable',()=>{let d=copy();d.episodes[0].deleted=true;ok(!C.resolveRef(d,'r-e01-1').ok)});
test('nonfinite, negative and overlong reference offsets rejected',()=>{for(const [a,b] of [[NaN,12],[0,Infinity],[-1,40],[0,999999999]]){let d=copy();d.refs[0].locator.start_ms=a;d.refs[0].locator.end_ms=b;ok(!C.resolveRef(d,d.refs[0].id).ok)}});
test('unexpected locator kind rejected',()=>{let d=copy();d.refs[0].locator.kind='remote_html';ok(!C.resolveRef(d,d.refs[0].id).ok)});
test('incorrect immutable media version rejected',()=>{let d=copy();d.refs[0].assetVersion=9;ok(!C.resolveRef(d,d.refs[0].id).ok)});
test('correction preserves old text and marks old citation stale',()=>{let d=copy(),e=d.episodes[0],s=e.segments[0],old=s.text;C.correctSegment(d,e.id,s.id,'新的核对文字');eq(s.history[0].text,old);ok(C.resolveRef(d,d.refs[0].id).stale)});
test('blank correction rejected',()=>assert.throws(()=>C.correctSegment(copy(),'e01','e01-s1','   ')));
test('draft depending on changed source becomes stale',()=>{let d=copy();C.correctSegment(d,'e01','e01-s1','明天四点。');eq(d.actions[0].status,'stale')});
test('saved event not silently rewritten after correction',()=>{let d=copy(),a=d.actions[0];C.saveAction(a,{}, {explicitConfirm:true},[]);C.correctSegment(d,'e01','e01-s1','明天四点。');eq(a.status,'saved_demo');eq(a.time,'15:00');eq(a.changeSuggested,true)});
test('three-level scene tree accepted',()=>ok(C.validTree([{id:'a'},{id:'b',parent:'a'},{id:'c',parent:'b'}])));
test('fourth level rejected',()=>ok(!C.validTree([{id:'a'},{id:'b',parent:'a'},{id:'c',parent:'b'},{id:'d',parent:'c'}])));
test('cycle rejected',()=>ok(!C.validTree([{id:'a',parent:'b'},{id:'b',parent:'a'}])));
test('duplicate and orphan scene IDs rejected',()=>{ok(!C.validTree([{id:'a'},{id:'a'}]));ok(!C.validTree([{id:'b',parent:'a'}]))});
test('graph has no dangling edge endpoints',()=>{let ids=new Set(original.graph.nodes.map(n=>n.id));for(const e of original.graph.edges)ok(ids.has(e.source)&&ids.has(e.target),e.id)});
test('graph identifiers and edge IDs unique',()=>{eq(new Set(original.graph.nodes.map(n=>n.id)).size,original.graph.nodes.length);eq(new Set(original.graph.edges.map(e=>e.id)).size,original.graph.edges.length)});
test('graph every cited source exists',()=>{for(const n of original.graph.nodes)for(const id of n.refs||[])ok(original.refs.some(r=>r.id===id),n.id)});
test('graph one-hop expansion actually includes neighbors',()=>{let g=C.graphNeighborhood(original.graph,['decision'],1);ok(g.nodes.length>1);for(const e of g.edges){ok(g.nodes.some(n=>n.id===e.source));ok(g.nodes.some(n=>n.id===e.target))}});
test('graph depth zero only contains selected node',()=>eq(C.graphNeighborhood(original.graph,['decision'],0).nodes.map(n=>n.id),['decision']));
test('no manufactured proven-causal relation',()=>ok(!original.graph.edges.some(e=>e.type==='causal_supported'||e.type==='causes')));
test('default no calendar write',()=>ok(!C.evaluateAction(copy().actions[0]).allowed));
test('explicit confirmation allows one valid self event',()=>ok(C.evaluateAction(copy().actions[0],{},{explicitConfirm:true}).allowed));
test('preauthorization permits bounded self event',()=>ok(C.evaluateAction(copy().actions[0],{enabled:true,selfOnly:true,allowEvents:true,until:'2026-10-18T00:00:00+08:00'}).allowed));
test('expired preauthorization rejected',()=>ok(!C.evaluateAction(copy().actions[0],{enabled:true,selfOnly:true,allowEvents:true,until:'2026-10-16T00:00:00+08:00'}).allowed));
test('wish is never executed even with authorization',()=>ok(!C.evaluateAction(copy().actions[3],{enabled:true,selfOnly:true,allowEvents:true},{explicitConfirm:true}).allowed));
test('ambiguous action remains pending details',()=>ok(!C.evaluateAction(copy().actions[2],{},{explicitConfirm:true}).allowed));
test('other-person event is not auto-managed',()=>{let a=copy().actions[0];a.subject='judge';ok(!C.evaluateAction(a,{},{explicitConfirm:true}).allowed)});
test('revoked, stale, conflict states block execution',()=>{for(const ctx of [{revoked:true},{sourceStale:true},{conflict:true}])ok(!C.evaluateAction(copy().actions[0],{},{explicitConfirm:true,...ctx}).allowed)});
test('nonfinite duration rejected',()=>{let a=copy().actions[0];a.duration=Infinity;ok(!C.evaluateAction(a,{},{explicitConfirm:true}).allowed)});
test('calendar retry does not add duplicate receipt',()=>{let a=copy().actions[0],r=[];ok(C.saveAction(a,{},{explicitConfirm:true},r).allowed);ok(!C.saveAction(a,{},{explicitConfirm:true},r).allowed);eq(r.length,1)});
test('cancelled event not rebuilt',()=>{let a=copy().actions[0];a.status='cancelled';ok(!C.evaluateAction(a,{},{explicitConfirm:true}).allowed)});
test('calendar overlap detected, adjacent boundary accepted',()=>{let d=copy(),a=d.actions[0];a.status='saved_demo';let b={...a,id:'other',time:'15:15',status:'draft'};eq(C.conflicts(d,b).length,1);b.time='15:30';eq(C.conflicts(d,b).length,0)});
test('ICS is valid-sized CRLF lines with UTC time and stable UID',()=>{let a=copy().actions[0];a.title='课程，讨论；记录\n下一步'.repeat(12);let s=C.icsEvent(a);ok(s.includes('DTSTART:20261017T070000Z'));ok(s.includes('UID:voicelog-a-ceremony@local.demo'));ok(s.includes('\\n'));for(const l of s.split('\r\n'))ok(Buffer.byteLength(l)<=75)});
test('source-sharing/graph interpretation contains no personality label fields',()=>{for(const i of original.interpretations||[])ok(!('personalityScore' in i)&&!('affectionScore' in i))});
const report={kind:'synthetic unit/property tests, no live services',passed:out.filter(x=>x.passed).length,failed:out.filter(x=>!x.passed).length,checks:out};const output=path.join(root,'reports','ui-merge','data_checks.json');fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2));console.log('DATA',report.passed,'passed',report.failed,'failed');process.exitCode=report.failed?1:0;
