'use strict';
const FIXTURE=JSON.parse(document.getElementById('fixture').textContent);
const clone=x=>JSON.parse(JSON.stringify(x));
const C=VCore;
const STORAGE_KEY='voicelog-ui-merge-v1';
let DATA=clone(FIXTURE),store={policy:{enabled:false,selfOnly:true,allowEvents:true},receipts:[],notes:[],messages:[],deletedRefs:[],candidateChoices:{},rejectedCandidates:[],replyDrafts:{},chatDrafts:{},glassLevel:65};
try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved&&saved.version===FIXTURE.version&&saved.data&&saved.store){DATA=saved.data;store={...store,...saved.store,replyDrafts:saved.store.replyDrafts||{}}}}catch(e){}
const S={expandedBlock:'b-am',graphScope:{kind:'all'},peopleStable:false,peopleOrder:[],groupFilter:'全部',graphFull:false,route:'home',homeMode:'time',date:DATA.dates[0],expanded:'b-am',tab:'总览',scene:'collaboration',selectedEpisode:'e02',focus:590,peopleWindow:{startMinute:540,endMinute:660},personTab:'理解',calendarDate:store.calendarDate||DATA.dates[1],calendarMonthOpen:false,calendarFilter:'all',person:'lin',sceneFilter:'全部',scope:{kind:'date',id:DATA.dates[0]},stack:[],sheet:null,record:'idle',recordSeconds:0,recordTimer:null,connected:true,voice:'idle',selectedNode:null,overlayBack:[],playing:false,search:'',scrollMemory:{},questionBusy:false,ablation:'full'};
const audios=new Map();let playingAudio=null,toastTimer,voiceTimer,returnFocus=null;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ICONS={home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z',layers:'m12 3 9 5-9 5-9-5z M3 12l9 5 9-5 M3 16l9 5 9-5',chat:'M4 4h16v12H8l-4 4z M8 8h8 M8 12h5',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M5 21v-3a7 7 0 0 1 14 0v3',mic:'M9 4a3 3 0 0 1 6 0v8a3 3 0 0 1-6 0z M5 10v2a7 7 0 0 0 14 0v-2 M12 19v3 M9 22h6',wave:'M3 10v4 M7 5v14 M11 2v20 M15 7v10 M19 4v16 M23 9v6',calendar:'M4 5h16v16H4z M8 2v6 M16 2v6 M4 10h16 M8 14h2 M14 14h2',chevron:'m9 5 7 7-7 7',down:'m6 9 6 6 6-6',back:'m14 5-7 7 7 7',close:'m6 6 12 12 M18 6 6 18',plus:'M12 4v16 M4 12h16',check:'m5 12 4 4L19 6',book:'M12 5c-3-3-7-3-9-2v16c4-1 7 0 9 2 2-2 5-3 9-2V3c-2-1-6-1-9 2z M12 5v16',cup:'M4 4h12v8a6 6 0 0 1-12 0z M16 5h2a3 3 0 0 1 0 6h-2 M2 21h18',moon:'M21 13A9 9 0 0 1 11 3 9 9 0 1 0 21 13',code:'m8 5-6 7 6 7 M16 5l6 7-6 7 M14 3l-4 18',spark:'m12 2 2.4 7.6L22 12l-7.6 2.4L12 22l-2.4-7.6L2 12l7.6-2.4z',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 7v5l3 2',play:'m8 4 12 8-12 8z',pause:'M8 5v14 M16 5v14',stop:'M6 6h12v12H6z',arrow:'M4 12h16 M14 6l6 6-6 6',send:'m3 3 18 9-18 9 4-9z M7 12h14',search:'M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0 M15 15l6 6',more:'M5 12h.01 M12 12h.01 M19 12h.01',link:'m9 15 6-6 M9 6l2-2a5 5 0 0 1 7 7l-2 2 M15 18l-2 2a5 5 0 0 1-7-7l2-2',shield:'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6z M8 12l3 3 5-6',download:'M12 3v12 M6 10l6 6 6-6 M4 17v4h16v-4',settings:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',undo:'M8 4 3 9l5 5 M3 9h11a7 7 0 0 1 0 14',people:'M9 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0 M18 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0 M1 21v-4a5 5 0 0 1 10 0v4 M12 14a5 5 0 0 1 9 4v3',timeline:'M5 3v18 M4 6h2 M4 12h2 M4 18h2 M10 6h11 M10 12h7 M10 18h9',tag:'M3 3h9l9 9-9 9-9-9z M7 7h.01',edit:'m14 4 6 6 M3 21l5-1L21 7l-5-5L3 15z',lock:'M6 10h12v11H6z M8 10V6a4 4 0 0 1 8 0v4',info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 11v6 M12 7h.01',folder:'M3 6h7l2 3h9v12H3z',refresh:'M20 8A8 8 0 1 0 21 14 M20 3v5h-5'};
ICONS.grip='M9 4h.01 M15 4h.01 M9 10h.01 M15 10h.01 M9 16h.01 M15 16h.01 M9 22h.01 M15 22h.01';
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${ICONS[name]||ICONS.layers}"/></svg>`;
const b=(act,label,cls='pill',extra='')=>`<button type="button" class="${cls}" data-act="${act}" ${extra}>${label}</button>`;
const person=id=>DATA.persons.find(p=>p.id===id)||{name:'未确认说话人',initial:'?',color:'#7b8973'};
const av=id=>`<span class="avatar" style="color:${person(id).color}">${esc(person(id).initial)}</span>`;
const shortTime=t=>t.slice(11,16);
const dur=(st,en)=>Math.round((C.ms(en)-C.ms(st))/60000);
const fmtMin=n=>n>=60?`${Math.floor(n/60)}小时${n%60?Math.round(n%60)+'分':''}`:`${Math.round(n)}分钟`;
const scopeLabel=()=>S.scope.kind==='block'?(DATA.blocks.find(b=>b.id===S.scope.id)?.title||'这段时间'):S.scope.kind==='date'?'10.'+S.scope.id.slice(-2)+' · 当天':S.scope.kind==='scene'?(DATA.scenes.find(s=>s.id===S.scope.id)?.name||'场景'):S.scope.kind==='episode'?(DATA.episodes.find(e=>e.id===S.scope.id)?.title||'当前记录'):S.scope.kind==='person'?person(S.scope.id).name:S.scope.kind==='project'?'VoiceLog · 项目':'全部可用记录';
const ref=(id,label)=>b('ref',esc(label||id.replace('r-e','').replace('-',':')),'ref',`data-id="${esc(id)}" aria-label="查看来源 ${esc(id)}"`);
function persist(){try{store.calendarDate=S.calendarDate||store.calendarDate;localStorage.setItem(STORAGE_KEY,JSON.stringify({version:FIXTURE.version,data:DATA,store}))}catch(e){toast('浏览器未允许保存，本次状态保留到页面关闭。')}}
function toast(text){clearTimeout(toastTimer);$('#toast-root').innerHTML=`<div class="toast">${esc(text)}</div>`;toastTimer=setTimeout(()=>$('#toast-root').innerHTML='',3200)}
function answer(q,scope=clone(S.scope)){const allowed=id=>C.resolveRef(DATA,id,scope).ok;let text='',refs=[],action='';if(/颁奖|领奖|精妙/.test(q)){text='今天最精妙的一步，是把复杂的一天收成能展开的几段。明天 15:00 有“参加颁奖环节”的明确示例安排；“上台领奖”来自玩笑，只留作愿望便签，不会当成获奖事实。';refs=['r-e01-1','r-e10-2'];action='calendar'}else if(/谁|多久|时长|最多/.test(q)){const ids=new Set(DATA.refs.filter(r=>allowed(r.id)).map(r=>r.recordingId));const scoped={...DATA,episodes:DATA.episodes.filter(e=>ids.has(e.id)),encounters:DATA.encounters.filter(e=>ids.has(e.episodeId)&&(scope.kind!=='person'||e.personId===scope.id))};let p=C.peopleStats(scoped,scope.kind==='date'?scope.id:'all').filter(p=>p.minutes>0);if(p.length){text=`当前选定范围内，与${p[0].name}的已确认交流区间合并后为 ${Math.round(p[0].minutes)} 分钟。按已确认、已记录区间去重统计。`;const es=[...new Set(scoped.encounters.filter(e=>e.personId===p[0].id).map(e=>e.episodeId))];refs=es.map(e=>DATA.refs.find(r=>r.recordingId===e&&allowed(r.id))?.id).filter(Boolean).slice(0,4);action='relations'}else{text='当前选定范围没有可汇总的已确认交流区间。可以查看已有原话，不推断未记录的陪伴时间。';refs=[]}}else if(/评审|评委/.test(q)){text='这段反馈明确认可时间线，也要求人物分析能打开原话。当前更有依据的理解是：他希望核对分析来源，同时关心一天是否容易看懂。可以回应：“我直接打开这条原话，再从它回到当天的变化。” 这些反馈没有说明最终评分或获奖决定。';refs=['r-e15-1','r-e15-2'];action='relations'}else if(/小林|担心|意图|回复/.test(q)){text='小林这段话明确提到“第一次进来找不到录音按钮”。较直接的解释是他在关心入口可达性，而非否定整套方案。你可以回应：“我先把录音入口留在第一屏，改完你再帮我走一次流程。” 这是一种回复建议，不能据此判断他长期是什么样的人。';refs=['r-e08-1','r-e08-2'];action='relations'}else if(/明天|安排|日历|承诺/.test(q)){text='示例资料里，明天 09:30 有联调、15:00 有颁奖环节；今晚发新版尚无具体时间，先保留为待办。你可以逐条确认，或开启仅限本人、时间明确且无冲突的自动规则。';refs=['r-e07-1','r-e01-1','r-e07-3'];action='calendar'}else if(/重点|并集|复习|老师|讲解/.test(q)){text='这段答疑的重点是：同一人的重叠交流区间先求并集，再累计时长。第二个重点是沉默无法证明离开。你可以回到原话核对，再打开场景里的动态区间讲解。';refs=['r-e04-1','r-e04-2'];action='relations'}else if(/方向|变化|今天|复盘|项目/.test(q)){text='今天的记录把方向收到了“开发者的一天”：09:15 决定先做白天；10:40 的访谈强调先看到刚才；16:20 再把录音入口放回第一屏。这几段分别留下决定、用户原话和具体修改，不把它们揉成一段无出处的总结。';refs=['r-e02-3','r-e03-1','r-e08-2'];action='recap'}else{let found=DATA.episodes.filter(e=>e.segments.length&&C.resolveRef(DATA,`r-${e.id}-1`,scope).ok).find(e=>q.split(/[，。 ?？]/).some(k=>k.length>1&&(e.title+e.summary+e.segments.map(s=>s.text).join('')).includes(k)));if(found){text=found.summary+' 可以沿原话继续查看。';refs=[`r-${found.id}-1`]}else text='当前范围内，没有足够的示例依据回答这个问题。你可以换一个场景、扩大范围，或补充相关记录。我不会编造来源。'}const filtered=refs.filter(allowed);if(refs.length&&!filtered.length){text='当前范围没有这条问题所需的资料。点顶部范围可以切换到当天、项目或相关人物；本次不会自动跨出你选的范围。';refs=[];action=''}else if(filtered.length<refs.length){text='在当前范围内，我找到以下原话：\n'+filtered.map(id=>C.resolveRef(DATA,id,scope).segment.text).join('\n')+'\n其他记录不在本次范围，尚未纳入回答。';refs=filtered;action=''}else refs=filtered;return {text,refs,action}}
function sendQuestion(q){q=q.trim();if(!q||S.questionBusy)return;const requestScope=clone(S.scope),requestKey=JSON.stringify(requestScope);store.chatDrafts??={};store.chatDrafts[requestKey]='';store.messages.push({role:'user',text:q,scopeKey:requestKey});S.questionBusy=true;render();setTimeout(()=>{store.messages.push({role:'assistant',...answer(q,requestScope),scopeKey:requestKey});S.questionBusy=false;persist();render();const t=$('#chat-thread');if(t)t.scrollTop=t.scrollHeight},380)}
function clock(sec){return Math.floor(sec/3600).toString().padStart(2,'0')+':'+Math.floor(sec/60%60).toString().padStart(2,'0')+':'+Math.floor(sec%60).toString().padStart(2,'0')}
function oldStartRecording(){if(S.record==='idle'){S.record='recording';S.recordSeconds=0;S.recordTimer=setInterval(()=>{if(S.record==='recording'){S.recordSeconds++;const clockEl=$('#record-clock');if(clockEl)clockEl.textContent=clock(S.recordSeconds)}},1000)}openSheet('record');header()}
function oldStopRecording(){if(S.record==='syncing'||S.record==='idle')return;let note=$('#record-note')?.value.trim()||'';clearInterval(S.recordTimer);S.record='syncing';renderSheet();setTimeout(()=>{S.record='idle';const id='manual-'+Date.now();const day=S.date==='all'?DATA.dates[0]:S.date;const e={id,date:day,start:day+'T21:05:00+08:00',end:day+'T21:06:00+08:00',kind:'reflection',domain:'生活',projectId:'voicelog-day',title:'刚留下的一条笔记',summary:note||'示例记录结束。没有录音，仅保存本次控制状态。',participants:[],segments:[],items:[note||'无语音内容'],source:'manual_note',status:'ready',revision:1,sound:{status:'not_collected',label:'原型未采集音频',events:[]},public:true};DATA.episodes.push(e);DATA.episodes.sort((a,b)=>C.ms(a.start)-C.ms(b.start));persist();closeSheet();S.route='home';S.homeMode='time';S.expanded=id;render();setTimeout(()=>document.querySelector(`[data-episode="${id}"]`)?.scrollIntoView({block:'center',behavior:'smooth'}),30);toast('模拟记录结束；保存的是本人笔记，没有生成音频。')},600)}
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type}));let a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function bindAudio(id){const inp=document.createElement('input');inp.type='file';inp.accept='audio/*';inp.onchange=()=>{let file=inp.files[0];if(!file)return;let prev=audios.get(id);if(prev)URL.revokeObjectURL(prev.url);audios.set(id,{name:file.name,url:URL.createObjectURL(file)});render();toast('已绑定本地文件，仅供本机定位试听；不会上传。')};inp.click()}
function legacyDispatch(act,d={}){
 switch(act){
 case 'nav':S.stack=[];S.route=d.route;S.sheet=null;S.tab='总览';if(S.route==='chat')S.scope={kind:'date',id:S.date==='all'?DATA.dates[0]:S.date};render();$('#content').scrollTop=0;break;
 case 'back':back();break;case 'close-sheet':closeSheet();break;
 case 'about':openSheet('about');break;case 'device':navigate('device');break;case 'privacy':navigate('privacy');break;case 'calendar':navigate('calendar');break;case 'recap':navigate('recap');break;case 'sleep':navigate('sleep');break;case 'search':navigate('search');break;case 'learning':navigate('learning');break;
 case 'date':S.date=d.date;S.expanded=d.date===DATA.dates[1]?'e12':'e02';render();$('#content').scrollTop=0;break;
 case 'home-mode':S.scrollMemory[S.homeMode]=$('#content').scrollTop;S.homeMode=d.mode;render();$('#content').scrollTop=S.scrollMemory[d.mode]||0;break;
 case 'expand':{if(S.ablation==='flat'){navigate('episode',{selectedEpisode:d.id,recordTab:'记录'});break}const el=document.querySelector(`[data-episode="${d.id}"]`);const y=el?.getBoundingClientRect().top;S.expanded=S.expanded===d.id?null:d.id;render();const el2=document.querySelector(`[data-episode="${d.id}"]`);if(el2&&y)$('#content').scrollTop+=el2.getBoundingClientRect().top-y;break}
 case 'episode':navigate('episode',{selectedEpisode:d.id,recordTab:'记录',highlight:null});break;
 case 'scene':if(d.id==='sleep')navigate('sleep');else navigate('scene',{scene:d.id,tab:'总览'});break;
 case 'project':navigate('scene',{scene:'project',tab:'总览'});break;
 case 'tab':S.tab=d.tab;render();$('#content').scrollTop=0;break;
 case 'record-tab':S.recordTab=d.tab;render();break;
 case 'scene-filter':S.sceneFilter=d.filter;render();break;
 case 'person':navigate('person',{person:d.id});break;
 case 'graph-view':S.table=d.table==='1';render();break;
 case 'node':S.selectedNode=d.id;render();break;
 case 'relations':navigate('relations');break;
 case 'ask-episode':navigate('chat',{scope:{kind:'episode',id:d.id}});break;
 case 'ask-scene':navigate('chat',{scope:{kind:S.scene==='project'?'project':'scene',id:S.scene==='project'?'voicelog-day':S.scene}});break;
 case 'ask-person':navigate('chat',{scope:{kind:'person',id:S.person}});break;
 case 'ask-project':navigate('chat',{scope:{kind:'project',id:'voicelog-day'}});break;
 case 'ask-day':navigate('chat',{scope:{kind:'date',id:S.date==='all'?DATA.dates[0]:S.date}});break;
 case 'ask-learning':navigate('chat',{scope:{kind:'scene',id:'learning'}});break;
 case 'quick-question':sendQuestion(d.question);break;
 case 'scope':openSheet('scope');break;case 'set-scope':S.scope={kind:d.kind,id:d.id};closeSheet();render();break;
 case 'ref':openSheet('ref',{id:d.id});break;
 case 'source-record':closeSheet();navigate('episode',{selectedEpisode:d.id,recordTab:'记录',highlight:d.segment});setTimeout(()=>document.querySelector(`[data-segment="${d.segment}"]`)?.scrollIntoView({block:'center'}),30);break;
 case 'correct':openSheet('correct',{id:d.id,segment:d.segment});break;
 case 'confirm-correction':{let text=$('#correction-text').value;try{C.correctSegment(DATA,d.id,d.segment,text);persist();closeSheet();render();toast('已保存新版本；相关结果待更新，已有日历只提出变更。')}catch(e){toast(e.message)}break}
 case 'note':openSheet('note',{id:d.id});break;
 case 'save-note':{let text=$('#note-text').value.trim();if(!text){toast('先写一句想留下的话。');break}store.notes.push({episodeId:d.id,text});persist();closeSheet();render();break}
 case 'record':startRecording();break;
 case 'pause-record':if(S.record==='recording')S.record='paused';else if(S.record==='paused')S.record='recording';renderSheet();header();break;
 case 'mark-record':toast('模拟重点标记已留下；实际按键回执需 SDK 接入。');break;
 case 'stop-record':stopRecording();break;
 case 'disconnect':S.connected=!S.connected;render();toast(S.connected?'模拟连接恢复，可继续核对状态。':'连接中断；原型不能确认设备是否继续录音。');break;
 case 'audio-play':if(playingAudio){playingAudio.paused?playingAudio.play().catch(()=>toast('音频未能播放，请换一个本地文件。')):playingAudio.pause()}break;
 case 'bind-audio':bindAudio(d.id);break;
 case 'policy':openSheet('policy');break;
 case 'confirm-policy':{store.policy.enabled=$('#policy-enable').checked;let n=0;if(store.policy.enabled)for(const a of DATA.actions){const r=C.resolveRef(DATA,a.sourceRef);if(C.saveAction(a,store.policy,{sourceStale:!r.ok||r.stale},store.receipts).allowed)n++}persist();closeSheet();render();toast(store.policy.enabled?`规则已开启，${n} 项符合条件的安排写入演示日历。`:'自动规则已关闭。');break}
 case 'save-action':{const a=DATA.actions.find(a=>a.id===d.id),r=C.resolveRef(DATA,a.sourceRef);let result=C.saveAction(a,store.policy,{explicitConfirm:true,sourceStale:!r.ok||r.stale},store.receipts);if(result.allowed){persist();render();toast('已存到演示日历；没有写入外部服务。')}else toast(result.reason);break}
 case 'edit-action':openSheet('action-edit',{id:d.id});break;
 case 'update-action':{const a=DATA.actions.find(a=>a.id===d.id),t=$('#act-title').value.trim(),date=$('#act-date').value,time=$('#act-time').value;if(!t||!date){toast('请补充标题和日期。');break}a.title=t;a.date=date;a.time=time||null;a.status=time?'draft':'needs_details';a.contentRevision=(a.contentRevision||1)+1;a.userEdited=true;const rr=C.resolveRef(DATA,a.sourceRef);if(rr.ok&&rr.stale){const nr={...clone(rr.ref),id:rr.ref.id+'-v'+rr.segment.revision,transcriptRevision:rr.segment.revision,text:rr.segment.text};if(!DATA.refs.some(r=>r.id===nr.id))DATA.refs.push(nr);a.sourceRef=nr.id;a.sourceRevision=rr.segment.revision;}persist();closeSheet();render();toast('草稿已更新，等待按新版本确认。');break}
 case 'cancel-action':{const a=DATA.actions.find(a=>a.id===d.id);a.status='cancelled';a.receipt=null;persist();render();toast('已撤销本地演示安排，不影响外部日历。');break}
 case 'ics':{const a=DATA.actions.find(a=>a.id===d.id);download('VoiceLog_'+a.id+'.ics',C.icsEvent(a),'text/calendar;charset=utf-8');toast('已导出日历文件；是否导入由你决定。');break}
 case 'wish':toast('已保留愿望便签，未创建任何领奖日程。');break;
 case 'voice':S.voice='listening';openSheet('voice');break;
 case 'voice-sample':S.voice='replying';renderSheet();voiceTimer=setTimeout(()=>{closeSheet();sendQuestion('明天有什么安排？')},650);break;
 case 'voice-interrupt':closeSheet();toast('已打断示例语音，切回文字。');$('#chat-input')?.focus();break;
 case 'reply':openSheet('reply');break;case 'copy-reply':navigator.clipboard?.writeText('我先把录音入口留在第一屏。改完你再帮我走一遍，看看还有哪一步不好找。').then(()=>toast('回复草稿已复制，未自动发送。')).catch(()=>toast('浏览器未允许复制，可以直接选中文字。'));break;
 case 'person-consent':openSheet('person-consent');break;case 'rename-person':openSheet('rename');break;
 case 'save-person-name':{const n=$('#person-name').value.trim();if(n){let p=person(S.person);p.name=n;p.initial=n.slice(0,1);persist();closeSheet();render()}break}
 case 'anonymize':{let p=person(S.person);p.name='匿名交流者';p.initial='匿';p.consent='session_only';DATA.encounters.forEach(e=>{if(e.personId===p.id)e.basis='session_anonymous'});persist();closeSheet();render();toast('已停止跨日已确认身份统计；记录中的匿名片段仍可回看。');break}
 case 'memory':openSheet('memory');break;case 'save-memory':store.preference=$('#memory-text').value.trim();persist();closeSheet();toast('已保存本人明确填写的偏好。');break;
 case 'export-data':download('VoiceLog_本机示例状态.json',JSON.stringify({disclaimer:DATA.fixtureNotice,data:DATA,store},null,2),'application/json');break;
 case 'ablation':S.ablation=d.mode;closeSheet();S.route='home';S.homeMode='time';render();toast(d.mode==='flat'?'消融视图：同样记录不再展开分块。':'已恢复场景折叠。');break;
 case 'reset':openSheet('reset');break;
 case 'confirm-reset':clearInterval(S.recordTimer);DATA=clone(FIXTURE);store={policy:{enabled:false,selfOnly:true,allowEvents:true},receipts:[],notes:[],messages:[],deletedRefs:[],glassLevel:65};applyGlassLevel(65);S.route='home';S.stack=[];S.record='idle';S.connected=true;S.date=DATA.dates[0];S.homeMode='time';S.expanded='b-am';S.expandedBlock='b-am';S.groupFilter='全部';S.peopleOrder=[];S.ablation='full';S.table=false;persist();closeSheet();render();$('#content').scrollTop=0;toast('已恢复初始示例。');break;
 default:console.warn('Unmapped interaction',act);toast('该入口暂未启用。')
 }}
