(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.VCore=factory()})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const ms=x=>typeof x==='number'?x:Date.parse(x);
function unionIntervals(input,window){let arr=input.map(x=>[ms(x[0]??x.start),ms(x[1]??x.end)]).filter(x=>Number.isFinite(x[0])&&Number.isFinite(x[1])&&x[1]>x[0]);if(window)arr=arr.map(x=>[Math.max(x[0],ms(window[0])),Math.min(x[1],ms(window[1]))]).filter(x=>x[1]>x[0]);arr.sort((a,b)=>a[0]-b[0]);let out=[];for(const v of arr){let last=out[out.length-1];if(last&&v[0]<=last[1])last[1]=Math.max(v[1],last[1]);else out.push([...v])}return out}
function clipIntervals(intervals,start,end){if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return [];return unionIntervals(intervals.map(([a,b])=>[Math.max(start,a),Math.min(end,b)]).filter(([a,b])=>b>a))}
function windowY(minute,start,end,height){if(!Number.isFinite(minute)||!Number.isFinite(start)||!Number.isFinite(end)||end<=start||!Number.isFinite(height)||height<0)return null;return (minute-start)/(end-start)*height}
function windowRange(intervals,start,end,height){if(windowY(start,start,end,height)===null)return [];return clipIntervals(intervals,start,end).map(([a,b])=>({start:a,end:b,top:(a-start)/(end-start)*height,height:(b-a)/(end-start)*height}))}
const durationMinutes=x=>unionIntervals(x).reduce((a,v)=>a+(v[1]-v[0])/60000,0);
const dayWindow=day=>[`${day}T00:00:00+08:00`,new Date(ms(`${day}T00:00:00+08:00`)+86400000).toISOString()];
function peopleStats(data,date){const window=date==='all'?null:dayWindow(date);return data.persons.filter(p=>p.id!=='me'&&p.consent==='confirmed_demo').map(p=>{const spans=data.encounters.filter(s=>s.personId===p.id&&s.basis==='confirmed_fixture'&&data.episodes.some(e=>e.id===s.episodeId&&!e.deleted&&e.public));const union=unionIntervals(spans,window);return {...p,minutes:durationMinutes(union),intervals:union}}).sort((a,b)=>b.minutes-a.minutes)}
function dayStats(data,date){const es=data.episodes.filter(e=>(date==='all'||e.date===date)&&e.status!=='preview'&&!e.deleted);const recorded=es.filter(e=>e.source==='audio_fixture');return {episodes:es.length,recordedMinutes:durationMinutes(recorded),people:peopleStats(data,date).filter(p=>p.minutes>0).length,privateMinutes:durationMinutes(es.filter(e=>e.source==='manual_private_gap')),days:date==='all'?data.dates.length:1}}
function resolveRef(data,id,scope={kind:'all'}){const r=data.refs.find(v=>v.id===id);if(!r)return {ok:false,reason:'来源不存在'};const e=data.episodes.find(v=>v.id===r.recordingId);if(!e||e.deleted||!e.public)return {ok:false,reason:'来源已撤回或不在可访问范围'};if(scope.kind==='episode'&&scope.id!==e.id)return {ok:false,reason:'超出当前录音范围'};if(scope.kind==='block'&&!(data.blocks.find(b=>b.id===scope.id)?.events||[]).includes(e.id))return {ok:false,reason:'超出当前时段范围'};if(scope.kind==='scene'&&scope.id!==e.kind)return {ok:false,reason:'超出当前场景范围'};if(scope.kind==='date'&&scope.id!==e.date)return {ok:false,reason:'超出当前日期范围'};if(scope.kind==='project'&&e.projectId!==scope.id)return {ok:false,reason:'超出当前项目范围'};if(scope.kind==='person'&&!e.participants.includes(scope.id))return {ok:false,reason:'超出当前人物范围'};if(r.assetVersion!==(e.mediaVersion||1))return {ok:false,reason:'原始资料版本不匹配'};const s=e.segments.find(v=>v.id===r.segmentId);const l=r.locator||{};if(!s||!['transcript_span','audio_span'].includes(l.kind)||!Number.isFinite(l.start_ms)||!Number.isFinite(l.end_ms)||l.start_ms<0||l.end_ms<=l.start_ms||l.end_ms>ms(e.end)-ms(e.start))return {ok:false,reason:'引用区间无效'};return {ok:true,ref:r,episode:e,segment:s,stale:r.transcriptRevision!==s.revision}}
function evaluateAction(a,policy={},ctx={}){if(['cancelled','dismissed'].includes(a.status))return {allowed:false,reason:'已撤销的安排不自动重建'};if(a.intent!=='explicit'||a.kind==='wish')return {allowed:false,reason:'愿望、玩笑或假设不执行'};if(a.subject!=='me')return {allowed:false,reason:'仅能代管本人安排'};if(!a.date||!a.time||!Number.isFinite(a.duration)||!Number.isFinite(ms(a.date+'T'+a.time+':00+08:00'))||a.duration<=0)return {allowed:false,reason:'缺少明确时间'};if(ctx.sourceStale||a.status==='stale')return {allowed:false,reason:'来源已修改，需要重新核对'};if(ctx.conflict)return {allowed:false,reason:'时间冲突，等待核对'};if(ctx.revoked)return {allowed:false,reason:'授权已撤销'};if(a.status==='saved_demo')return {allowed:false,reason:'已存在，无需重复创建'};if(ctx.explicitConfirm)return {allowed:true,basis:'one_time_confirmation'};if(policy.enabled&&policy.selfOnly&&policy.allowEvents&&(!policy.until||ms(a.date+'T'+a.time+':00+08:00')<=ms(policy.until)))return {allowed:true,basis:'bounded_pre_authorization'};return {allowed:false,reason:'待本人确认或开启有限自动化'}}
function saveAction(a,policy,ctx,receipts){const v=evaluateAction(a,policy,ctx);if(!v.allowed)return v;const key=`${a.id}@${a.contentRevision||1}`;let receipt=receipts.find(r=>r.key===key);if(!receipt){receipt={id:'demo-'+a.id,key,kind:'demo_calendar',status:'saved_demo'};receipts.push(receipt)}a.status='saved_demo';a.receipt=receipt.id;return {allowed:true,receipt}}
function correctSegment(data,episodeId,segmentId,text){if(!text.trim())throw Error('内容不能为空');const e=data.episodes.find(x=>x.id===episodeId);if(!e)throw Error('记录不存在');const s=e.segments.find(x=>x.id===segmentId);if(!s)throw Error('句子不存在');s.history=s.history||[];s.history.push({revision:s.revision,text:s.text});s.text=text.trim();s.revision++;e.revision++;e.analysisStale=true;const refs=data.refs.filter(r=>r.segmentId===segmentId).map(r=>r.id);for(const a of data.actions)if(refs.includes(a.sourceRef)){if(a.status==='saved_demo')a.changeSuggested=true;else if(a.kind!=='wish')a.status='stale'}return refs}
function validTree(nodes){const by=new Map(nodes.map(n=>[n.id,n]));if(by.size!==nodes.length)return false;for(const n of nodes){let q=n,seen=new Set(),depth=0;while(q){if(seen.has(q.id))return false;seen.add(q.id);if(++depth>3)return false;if(q.parent&&!by.has(q.parent))return false;q=q.parent?by.get(q.parent):null}}return true}
function escapeICS(s){return String(s??'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,')}
function utcStamp(x){return new Date(x).toISOString().replace(/[-:]/g,'').replace(/\.\d+Z/,'Z')}
function foldICS(line){let lines=[],part='',bytes=0;for(const ch of line){const n=new TextEncoder().encode(ch).length;if(bytes+n>73){lines.push(part);part=' '+ch;bytes=1+n}else{part+=ch;bytes+=n}}lines.push(part);return lines.join('\r\n')}
function icsEvent(a){if(!a.date||!a.time)throw Error('时间不完整');const start=ms(`${a.date}T${a.time}:00+08:00`);return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//VoiceLog//Demo Export//ZH','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:voicelog-${a.id}@local.demo`,`DTSTAMP:${utcStamp(Date.UTC(2026,8,26))}`,`DTSTART:${utcStamp(start)}`,`DTEND:${utcStamp(start+a.duration*60000)}`,`SUMMARY:${escapeICS(a.title)}`,`LOCATION:${escapeICS(a.place)}`,`DESCRIPTION:${escapeICS('产品演示资料，导出不等于已写入日历。'+a.description)}`,'END:VEVENT','END:VCALENDAR',''].map(foldICS).join('\r\n')}
function sceneBlocks(data,date,category='全部') {
 const blocks=(data.blocks||[]).filter(b=>(date==='all'||b.date===date)&&(category==='全部'||b.scene===category));
 return blocks.map(b=>({...b,items:b.events.map(id=>data.episodes.find(e=>e.id===id&&!e.deleted)).filter(Boolean)})).filter(b=>b.items.length).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));
}
function peopleOrder(data,date,minute,previous=[],stable=false,pin=null){
 const ids=[...new Set(data.encounters.filter(x=>x.start.startsWith(date)&&data.episodes.some(e=>e.id===x.episodeId&&!e.deleted)).map(x=>x.personId))];
 const prev=[...previous.filter(x=>ids.includes(x)),...ids.filter(x=>!previous.includes(x))];
 if(stable)return pin&&ids.includes(pin)?[pin,...prev.filter(x=>x!==pin)]:prev;
 const index=new Map(prev.map((id,i)=>[id,i]));
 const spans=id=>data.encounters.filter(x=>x.personId===id&&x.start.startsWith(date)&&data.episodes.some(e=>e.id===x.episodeId&&!e.deleted)).map(x=>[+x.start.slice(11,13)*60+ +x.start.slice(14,16),+x.end.slice(11,13)*60+ +x.end.slice(14,16)]);
 const score=id=>{let a=spans(id);if(a.some(([s,e])=>minute>=s&&minute<e))return 0;let dist=Math.min(...a.map(([s,e])=>Math.min(Math.abs(s-minute),Math.abs(e-minute))));return dist<=20?1:dist<=60?2:3};
 return prev.sort((a,b)=>a===b?0:a===pin?-1:b===pin?1:score(a)-score(b)||(index.get(a)-index.get(b)));
}
function graphNeighborhood(graph,seeds,depth=1){
 let ids=new Set(seeds),front=new Set(seeds);
 for(let n=0;n<depth;n++){let next=new Set();for(const e of graph.edges){if(front.has(e.source)&&!ids.has(e.target))next.add(e.target);if(front.has(e.target)&&!ids.has(e.source))next.add(e.source)};for(const x of next)ids.add(x);front=next}
 return {nodes:graph.nodes.filter(n=>ids.has(n.id)),edges:graph.edges.filter(e=>ids.has(e.source)&&ids.has(e.target))};
}
function conflicts(data,action){
 if(!action.time||!action.duration)return [];
 const start=ms(action.date+'T'+action.time+':00+08:00'),end=start+action.duration*60000;
 return data.actions.filter(a=>a.id!==action.id&&a.status==='saved_demo'&&a.time&&a.date===action.date&&ms(a.date+'T'+a.time+':00+08:00')<end&&ms(a.date+'T'+a.time+':00+08:00')+a.duration*60000>start);
}

return {sceneBlocks,peopleOrder,graphNeighborhood,conflicts,ms,unionIntervals,clipIntervals,windowY,windowRange,durationMinutes,dayWindow,peopleStats,dayStats,resolveRef,evaluateAction,saveAction,correctSegment,validTree,icsEvent};
});
