/* Cytoscape is vendored and inline. Graph data is a typed, cited view of records. */
const GRAPH_COLORS={project:'#245e48',block:'#91aa65',event:'#637cb4',source:'#175cdd',person:'#997861',concept:'#8581b2',action:'#b2934b'};
const GRAPH_FONT_STACK='"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei UI", "Microsoft YaHei", "Noto Sans CJK SC", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
const GRAPH_TYPES={project:'项目',block:'场景时段',event:'事情',source:'原话',person:'人物',concept:'要点',action:'安排'};
const EDGE_NAMES={contains:'包含',source:'原话',participant:'参与',derived:'整理自',supports:'支持',refines:'细化',used_in:'用于',related:'关联',proposes:'形成草稿',hypothesis:'待核对解释'};
function currentGraphScope(){return S.route==='scene'?{kind:S.scene==='project'?'project':'scene',id:S.scene==='project'?'voicelog-day':S.scene}:S.route==='person'?{kind:'person',id:S.person}:S.route==='episode'?{kind:'episode',id:S.selectedEpisode}:S.graphScope||{kind:'all'}}
function graphAllowed(scope){
 const all=DATA.graph;let eps=new Set(DATA.episodes.filter(e=>!e.deleted&&e.public&&e.status!=='preview').map(e=>e.id));
 if(scope?.kind==='date')eps=new Set([...eps].filter(id=>episode(id).date===scope.id));
 if(scope?.kind==='scene')eps=new Set([...eps].filter(id=>episode(id).kind===scope.id));
 if(scope?.kind==='episode')eps=new Set([scope.id].filter(id=>eps.has(id)));
 if(scope?.kind==='block')eps=new Set((DATA.blocks.find(b=>b.id===scope.id)?.events||[]).filter(id=>eps.has(id)));
 if(scope?.kind==='person')eps=new Set([...eps].filter(id=>episode(id).participants.includes(scope.id)));
 let ids=new Set(['project']);for(const n of all.nodes){if(n.episodeId&&eps.has(n.episodeId))ids.add(n.id);if(n.blockId&&DATA.blocks.find(b=>b.id===n.blockId)?.events.some(id=>eps.has(id)))ids.add(n.id);if(n.personId&&[...eps].some(id=>episode(id).participants.includes(n.personId)))ids.add(n.id);if(n.actionId&&(n.refs||[]).some(id=>eps.has(DATA.refs.find(r=>r.id===id)?.recordingId)))ids.add(n.id)}
 return {nodes:all.nodes.filter(n=>ids.has(n.id)),edges:all.edges.filter(e=>ids.has(e.source)&&ids.has(e.target))};
}
function graphSeed(scope,allowed){let id=scope?.kind==='episode'?scope.id:scope?.kind==='block'?scope.id:scope?.kind==='person'?'p-'+scope.id:scope?.kind==='scene'?(allowed.nodes.find(n=>n.type==='event')?.id||'project'):'decision';return allowed.nodes.some(n=>n.id===id)?id:'project'}
function graphPreviewMarkup(scope){return `<div class="graph-preview"><div class="graph-canvas" data-graph-preview="${esc(JSON.stringify(scope))}" tabindex="0" aria-label="局部关系图"></div><div class="graph-preview-head"><span class="tag">关联记忆</span>${b('open-full-graph',icon('plus'),'round small soft',`data-scope-json="${esc(JSON.stringify(scope))}" aria-label="打开完整关系图"`)}</div><div class="graph-preview-foot"><span>点选节点查看</span>${b('open-full-graph','完整关系图 '+icon('arrow'),'text-button',`data-scope-json="${esc(JSON.stringify(scope))}"`)}</div></div><div id="graph-inline-detail" class="graph-inline-detail"></div>`}
function relationView(scope){if(!scope||!scope.kind)scope=S.graphScope||{kind:'all'};S.graphScope=scope;let g=graphAllowed(scope);return `<div class="segmented" role="tablist">${b('graph-view','关系图',!S.table?'active':'','data-table="0"')}${b('graph-view','关系表',S.table?'active':'','data-table="1"')}</div>${S.table?`<table class="list-table"><thead><tr><th>内容</th><th>关系</th><th>关联内容</th></tr></thead><tbody>${g.edges.filter(e=>!['contains','participant'].includes(e.type)).slice(0,24).map(e=>`<tr><td>${b('graph-table-node',esc(g.nodes.find(n=>n.id===e.source)?.label),'text-button',`data-id="${e.source}"`)}</td><td>${EDGE_NAMES[e.type]}</td><td>${b('graph-table-node',esc(g.nodes.find(n=>n.id===e.target)?.label),'text-button',`data-id="${e.target}"`)}</td></tr>`).join('')}</tbody></table>`:graphPreviewMarkup(scope)}${b('open-full-graph',icon('link')+' 打开完整关系图','fullbtn secondary',`data-scope-json="${esc(JSON.stringify(scope))}"`)}`}
function mountGraphs(){const el=document.querySelector('[data-graph-preview]');if(el)graphView=new KnowledgeGraph(el,JSON.parse(el.dataset.graphPreview),false)}
class KnowledgeGraph{
 constructor(el,scope,full){this.el=el;this.scope=scope;this.full=full;this.g=graphAllowed(scope);this.seed=graphSeed(scope,this.g);this.detail=false;this.kind='all';this.expanded=new Set();this.selected=null;this.dead=false;this.cache=new Map();this.baseSet=new Set();this.zoomValue=1;this.timer=null;
 const seedNode=this.g.nodes.find(n=>n.id===this.seed);if(full){this.baseSet=new Set(this.g.nodes.filter(n=>n.type!=='source').map(n=>n.id))}else{const near=C.graphNeighborhood(this.g,[this.seed],1);this.baseSet=new Set(near.nodes.slice(0,10).map(n=>n.id));this.baseSet.add(this.seed)}
 this.cy=cytoscape({container:el,elements:[],style:this.styles(),layout:{name:'preset'},minZoom:.18,maxZoom:2.6,wheelSensitivity:.18,textureOnViewport:false,hideEdgesOnViewport:false,pixelRatio:Math.min(devicePixelRatio||1,2),motionBlur:false,boxSelectionEnabled:false,autoungrabify:false,touchTapThreshold:8,desktopTapThreshold:5});
 this.renderData(false);this.cy.on('tap','node',ev=>this.select(ev.target.id()));this.cy.on('tap','edge',ev=>this.selectEdge(ev.target.id()));this.cy.on('tap',ev=>{if(ev.target===this.cy)this.clear()});
 this.cy.on('mouseover','node',ev=>{if(!window.matchMedia('(hover:hover) and (pointer:fine)').matches)return;this.highlight(ev.target.id(),false)});this.cy.on('mouseout','node',()=>{if(this.selected)this.highlight(this.selected,true);else this.cy.elements().removeClass('dim near focal')});
 this.cy.on('grab','node',ev=>this.startLinkedDrag(ev.target));this.cy.on('drag','node',ev=>this.updateLinkedDrag(ev.target));this.cy.on('free','node',ev=>this.finishLinkedDrag(ev.target));this.cy.on('zoom pan',()=>{this.updateZoom();this.saveCamera()});
 this.ro=new ResizeObserver(()=>{if(this.dead)return;this.cy.resize()});this.ro.observe(el);el.addEventListener('keydown',this.keyHandler=e=>{if(['+','=','-','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','0'].includes(e.key)){e.preventDefault();if(e.key==='+'||e.key==='=')this.zoomBy(1.22);else if(e.key==='-')this.zoomBy(.82);else if(e.key==='0')this.fit();else {let p=this.cy.pan();const step=e.shiftKey?100:40;p.x+=e.key==='ArrowLeft'?step:e.key==='ArrowRight'?-step:0;p.y+=e.key==='ArrowUp'?step:e.key==='ArrowDown'?-step:0;this.cy.pan(p)}}});
 if(full){this.clear();requestAnimationFrame(()=>requestAnimationFrame(()=>{if(!this.dead&&!this.selected){this.cy.resize();this.phoneOverview()}}))}else this.select(this.seed);
 }
 styles(){return [
 {selector:'node',style:{'width':14,'height':14,'background-color':'data(color)','border-width':2,'border-color':'#fbfcf8','label':'data(short)','font-family':GRAPH_FONT_STACK,'font-size':this.full?11:12,'color':'#54664b','text-valign':'bottom','text-halign':'center','text-margin-y':6,'text-wrap':'wrap','text-max-width':92,'min-zoomed-font-size':7,'text-background-color':'#fbfcf8','text-background-opacity':.87,'text-background-padding':2,'overlay-opacity':0,'transition-property':'opacity, text-opacity, border-color, border-width','transition-duration':reduced()?0:140}},
 {selector:'node[type="project"]',style:{width:25,height:25,'font-size':14,'font-weight':600}},
 {selector:'node[type="block"]',style:{width:20,height:20,'font-size':12}},
 {selector:'node[type="source"]',style:{width:10,height:10,'font-size':10}},
 ...(this.full?[{selector:'node[type="event"]',style:{label:''}},{selector:'node[type="source"]',style:{label:''}}]:[]),
 {selector:'node.bridge',style:{label:'data(short)','font-size':11,'text-max-width':108}},
 {selector:'node.filtered-primary',style:{width:19,height:19,'font-size':12}},
 {selector:'edge',style:{width:1,'line-color':'#c9d3bd','curve-style':'bezier','target-arrow-shape':'none','opacity':.6,'overlay-opacity':0,'label':'','font-size':9,'text-background-color':'#f7f8f2','text-background-opacity':1,'text-background-padding':3,'transition-property':'opacity,line-color','transition-duration':reduced()?0:140}},
 {selector:'edge.filtered-link',style:{width:1.7,'line-color':'#89a775',opacity:.88}},
 {selector:'edge[type="hypothesis"]',style:{'line-style':'dashed','line-color':'#c29461'}},
 {selector:'.dim',style:{opacity:.12,'text-opacity':.12}},
 {selector:'node.near',style:{opacity:1,'text-opacity':1,'border-color':'#f7f8f2',label:'data(short)'}},
 {selector:'node.focal',style:{'border-width':5,'border-color':'#bedf55','z-index':99,'color':'#193e2c','font-weight':600,'text-opacity':1,label:'data(short)'}},
 {selector:'edge.near',style:{opacity:1,width:1.8,'line-color':'#94aa62','target-arrow-shape':'triangle','arrow-scale':.5}},
 {selector:'edge.chosen',style:{opacity:1,width:2,'line-color':'#b09036','label':'data(edgeLabel)','text-rotation':'autorotate'}}
 ]}
 visibleNodes(){
  const available=this.detail?new Set(this.g.nodes.map(n=>n.id)):new Set(this.baseSet);
  for(const id of this.expanded){const near=C.graphNeighborhood(this.g,[id],1);near.nodes.forEach(n=>available.add(n.id))}
  if(this.kind==='all')return this.g.nodes.filter(n=>available.has(n.id));
  const primary=new Set(this.g.nodes.filter(n=>available.has(n.id)&&n.type===this.kind).map(n=>n.id));
  const keep=new Set(primary),bridgeTypes=this.kind==='person'?new Set(['participant']):this.kind==='concept'?new Set(['derived','used_in']):new Set();
  for(const edge of this.g.edges)if(bridgeTypes.has(edge.type)&&available.has(edge.source)&&available.has(edge.target)&&(primary.has(edge.source)||primary.has(edge.target))){keep.add(edge.source);keep.add(edge.target)}
  if(this.detail)for(const edge of this.g.edges)if(edge.type==='source'&&keep.has(edge.source)&&available.has(edge.target))keep.add(edge.target);
  return this.g.nodes.filter(n=>keep.has(n.id));
 }
 renderData(animate=true){
 this.stopLinkedMotion();
 this.cy.stop(true,false);this.cy.elements().stop(true,false);const before=this.cy.nodes().map(n=>({id:n.id(),...n.position()}));before.forEach(n=>this.cache.set(n.id,{x:n.x,y:n.y}));let nodes=this.visibleNodes(),ids=new Set(nodes.map(n=>n.id)),edges=this.g.edges.filter(e=>ids.has(e.source)&&ids.has(e.target));
 const fullCenter={project:[500,340],block:[500,340],event:[500,340],concept:[600,340],person:[260,300],action:[700,500],source:[500,340]};
 const elements=nodes.map((n,i)=>{let pos=this.cache.get(n.id);if(!pos){const bi=DATA.blocks.findIndex(b=>b.id===n.id||b.events.includes(n.episodeId));const a=(Math.max(bi,0)/7)*Math.PI*2;const radius=n.type==='project'?0:220;const center=fullCenter[n.type]||[500,340];pos={x:center[0]+Math.cos(a)*radius+Math.cos(i*2.4)*55,y:center[1]+Math.sin(a)*radius+Math.sin(i*2.4)*55}}return {data:{...n,color:GRAPH_COLORS[n.type],short:n.label.length>13?n.label.slice(0,12)+'…':n.label},classes:this.kind!=='all'?(n.type==='event'?'bridge':n.type===this.kind?'filtered-primary':''):'',position:pos}}).concat(edges.map(e=>({data:{...e,edgeLabel:EDGE_NAMES[e.type]||e.type},classes:this.kind!=='all'?'filtered-link':''})));
 this.cy.json({elements});this.cy.elements().removeClass('dim near focal chosen');
 const filtered=this.full&&this.kind!=='all',repulsion=this.full?(filtered?9500:15500):5500,edgeLength=this.full?(filtered?100:115):65,spacing=this.full?(filtered?88:105):60;
 if(!animate||before.length===0){this.cy.layout({name:'cose',animate:false,fit:false,randomize:false,nodeDimensionsIncludeLabels:true,nodeRepulsion:()=>repulsion,idealEdgeLength:()=>edgeLength,edgeElasticity:()=>65,gravity:this.full ? .12 : .3,numIter:this.full ? 340 : 220,componentSpacing:spacing,initialTemp:100,coolingFactor:.95,minTemp:1}).run();this.compact();this.savePositions();this.fit(false)}
 else{this.cy.layout({name:'cose',animate:false,fit:false,randomize:false,nodeDimensionsIncludeLabels:true,nodeRepulsion:()=>repulsion,idealEdgeLength:()=>edgeLength,edgeElasticity:()=>65,gravity:this.full ? .12 : .3,numIter:this.full ? 270 : 180,componentSpacing:spacing,initialTemp:70,coolingFactor:.95,minTemp:1}).run();this.compact();if(!reduced()){const targets=this.cy.nodes().map(n=>({node:n,pos:{...n.position()},old:this.cache.get(n.id())}));targets.forEach(x=>{if(x.old){x.node.position(x.old);x.node.animate({position:x.pos},{duration:230,easing:'ease-in-out-cubic'})}})}}
 if(this.selected&&this.cy.getElementById(this.selected).length)this.highlight(this.selected,true);else if(this.selected){this.selected=null;this.detailPanel(null)}this.status();
 }
 compact(){if(this.full)return;const lengths=this.cy.edges().map(e=>{const a=e.source().position(),b=e.target().position();return Math.hypot(a.x-b.x,a.y-b.y)}).filter(x=>x>0).sort((a,b)=>a-b);if(!lengths.length)return;const factor=Math.min(1,102/lengths[Math.floor(lengths.length/2)]);const bb=this.cy.nodes().boundingBox(),cx=(bb.x1+bb.x2)/2,cy=(bb.y1+bb.y2)/2;this.cy.nodes().positions(n=>({x:cx+(n.position('x')-cx)*factor,y:cy+(n.position('y')-cy)*factor}))}
 linkedDistances(id){const links=new Map(this.cy.nodes().map(n=>[n.id(),[]]));this.cy.edges().forEach(e=>{const a=e.source().id(),b=e.target().id();links.get(a)?.push(b);links.get(b)?.push(a)});const distances=new Map([[id,0]]),queue=[id];for(let i=0;i<queue.length;i++){const current=queue[i],depth=distances.get(current);for(const next of links.get(current)||[])if(!distances.has(next)){distances.set(next,depth+1);queue.push(next)}}return distances}
 startLinkedDrag(node){this.stopLinkedMotion();const positions=new Map(this.cy.nodes().map(n=>[n.id(),{...n.position()}]));this.linkDrag={id:node.id(),origin:{...node.position()},positions,distances:this.linkedDistances(node.id()),delta:{x:0,y:0},held:true}}
 updateLinkedDrag(node){const drag=this.linkDrag;if(!drag||drag.id!==node.id())return;drag.delta={x:node.position('x')-drag.origin.x,y:node.position('y')-drag.origin.y};this.scheduleLinkedMotion()}
 finishLinkedDrag(node){const drag=this.linkDrag;if(!drag||drag.id!==node.id()){this.savePositions();return}this.updateLinkedDrag(node);drag.held=false;this.scheduleLinkedMotion()}
 scheduleLinkedMotion(){if(this.linkFrame||!this.linkDrag||this.dead)return;this.linkFrame=requestAnimationFrame(()=>{this.linkFrame=null;this.stepLinkedMotion()})}
 stepLinkedMotion(){const drag=this.linkDrag;if(!drag||this.dead)return;let gap=0;const immediate=reduced(),alpha=immediate?1:(drag.held ? .32 : .2);this.cy.batch(()=>{this.cy.nodes().forEach(n=>{if(n.id()===drag.id)return;const base=drag.positions.get(n.id());if(!base)return;const hops=drag.distances.get(n.id()),weight=hops===undefined ? .045 : Math.max(.05,.62*Math.pow(.5,hops-1));const target={x:base.x+drag.delta.x*weight,y:base.y+drag.delta.y*weight},p=n.position(),dx=target.x-p.x,dy=target.y-p.y;gap=Math.max(gap,Math.hypot(dx,dy));if(Math.abs(dx)+Math.abs(dy)>.02)n.position({x:p.x+dx*alpha,y:p.y+dy*alpha})})});if(gap>.25&&!immediate)this.scheduleLinkedMotion();else if(!drag.held){this.savePositions();this.linkDrag=null}}
 stopLinkedMotion(){if(this.linkFrame)cancelAnimationFrame(this.linkFrame);this.linkFrame=null;this.linkDrag=null}
 savePositions(){this.cy.nodes().forEach(n=>this.cache.set(n.id(),{...n.position()}))}
 saveCamera(){if(!this.full)S.previewCamera={pan:this.cy.pan(),zoom:this.cy.zoom()}}
 updateZoom(){this.zoomValue=this.cy.zoom();const el=this.full?$('#graph-zoom'):null;if(el)el.textContent=Math.round(this.zoomValue*100)+'%'}
 status(){if(this.full){const el=$('#graph-status');if(el)el.textContent=this.cy.nodes().length+' 节点 · '+this.cy.edges().length+' 关联'}this.updateZoom()}
 highlight(id,selected){const n=this.cy.getElementById(id);if(n.empty())return;const near=n.closedNeighborhood();this.cy.batch(()=>{this.cy.elements().addClass('dim').removeClass('near focal chosen');near.removeClass('dim').addClass('near');n.addClass('focal')});if(selected)this.selected=id}
 select(id,focus=false){if(!this.cy.getElementById(id).length){this.expanded.add(id);this.baseSet.add(id);this.renderData(true)}if(!this.cy.getElementById(id).length)return;this.selected=id;this.highlight(id,true);this.detailPanel(id);if(focus)this.focus();}
 clear(){this.selected=null;this.cy.elements().removeClass('dim near focal chosen');this.detailPanel(null)}
 selectEdge(id){const e=this.cy.getElementById(id);if(e.empty())return;this.cy.elements().addClass('dim').removeClass('near focal chosen');e.removeClass('dim').addClass('chosen');e.connectedNodes().removeClass('dim').addClass('near');this.detailPanel(null,e.data())}
 detailPanel(id,edgeData=null){
 const node=this.g.nodes.find(n=>n.id===id),target=this.full?$('#graph-inspector'):$('#graph-inline-detail');if(!target)return;
 if(this.full)target.closest('.graph-fullscreen')?.classList.toggle('has-selection',!!node||!!edgeData);
 if(edgeData){let source=this.g.nodes.find(n=>n.id===edgeData.source),dest=this.g.nodes.find(n=>n.id===edgeData.target);target.innerHTML=`<span class="tag">${esc(EDGE_NAMES[edgeData.type])}</span><h3>${esc(source?.label)} → ${esc(dest?.label)}</h3><p class="graph-state-note">${edgeData.type==='hypothesis'?'这是一种待核对解释。':edgeData.type==='contains'?'按本次记录的时间归属整理。':'这条线表示资料之间的关联。'}</p>${edgeData.refs.map((r,i)=>ref(r,two(i+1))).join('')}`;return}
 if(!node){target.innerHTML=this.full?`<span class="tag">关联记忆</span><h3>拖动图谱，点选查看</h3><p>查看人物、记录与原话之间的已有关系。双指缩放，点击下方“节点列表”可直接定位。</p>`:'选择一条记录，查看相关内容。';return}
 let refs=(node.refs||[]).filter(id=>C.resolveRef(DATA,id).ok),summary=node.type==='source'&&node.ref?C.resolveRef(DATA,node.ref).segment?.text:node.summary;const related=this.g.edges.filter(e=>e.source===id||e.target===id).slice(0,8);
 target.innerHTML=`<span class="tag">${GRAPH_TYPES[node.type]}</span>${this.full?b('graph-clear',icon('close'),'round small graph-clear','aria-label="取消选中"'):''}<h3 class="graph-focus-name">${esc(node.label)}</h3>${refs.some(r=>C.resolveRef(DATA,r).stale)?'<span class="tag amber">来源已有修订</span>':''}<p>${esc(summary||'')}</p>${refs.slice(0,3).map((r,i)=>ref(r,two(i+1))).join('')}<div class="actions-row" style="margin-top:12px">${b('graph-expand',icon('plus')+' 展开关联','pill',`data-id="${id}"`)}${b('graph-ask',icon('chat')+' 对话','pill dark',`data-id="${id}"`)}${node.episodeId?b('graph-record','原始记录','text-button',`data-id="${node.episodeId}"`):node.personId?b('graph-person','人物记录','text-button',`data-id="${node.personId}"`):''}</div>${this.full?`<div class="neighbor-list">${related.map(e=>{let oid=e.source===id?e.target:e.source,n=this.g.nodes.find(n=>n.id===oid);return `<button data-act="graph-select" data-id="${oid}"><span style="background:${GRAPH_COLORS[n.type]}"></span><span>${esc(n.label)}</span><small>${EDGE_NAMES[e.type]}</small></button>`}).join('')}</div>`:''}`;
 }
 zoomBy(factor){let z=Math.max(.18,Math.min(2.6,this.cy.zoom()*factor));this.cy.stop();this.cy.zoom({level:z,renderedPosition:{x:this.cy.width()/2,y:this.cy.height()/2}});this.updateZoom()}
 fit(animate=true){const eles=this.cy.elements();if(eles.empty())return;this.cy.stop();if(animate&&!reduced())this.cy.animate({fit:{eles,padding:this.full?80:42}},{duration:220,easing:'ease-out-cubic'});else this.cy.fit(eles,this.full?80:42);this.updateZoom()}
 phoneOverview(){this.fit(false);if(!this.full||this.cy.zoom()>=.58)return;const center=this.cy.getElementById(this.g.nodes.some(n=>n.id==='project')?'project':this.seed);if(center.empty())return;const z=.68,p=center.position();this.cy.viewport({zoom:z,pan:{x:this.cy.width()*.53-p.x*z,y:this.cy.height()*.55-p.y*z}});this.updateZoom()}
 focus(animate=true){this.cy.resize();if(!this.selected){this.fit(animate);return}const n=this.cy.getElementById(this.selected);if(n.empty()){this.selected=null;this.detailPanel(null);this.fit(animate);return}this.cy.stop();if(!this.full){this.cy.fit(n.closedNeighborhood(),38);return}const z=.9;const p=n.position(),pan={x:this.cy.width()/2-p.x*z,y:Math.max(125,this.cy.height()/2+25)-p.y*z};if(animate&&!reduced())this.cy.animate({pan,zoom:z},{duration:240,easing:'ease-out-cubic'});else this.cy.viewport({pan,zoom:z})}
 expand(id){this.expanded.add(id);this.baseSet.add(id);this.renderData(true);this.select(id);setTimeout(()=>{if(!this.dead)this.focus()},250)}
 toggleSources(){this.detail=!this.detail;this.renderData(true);const btn=$('#graph-sources');btn?.classList.toggle('active',this.detail);setTimeout(()=>{if(!this.dead)this.selected?this.focus():this.fit()},260)}
 filter(type){this.kind=type;this.renderData(true);setTimeout(()=>{if(!this.dead)this.selected?this.focus():this.fit()},260)}
 destroy(){this.dead=true;this.stopLinkedMotion();this.ro.disconnect();this.el.removeEventListener('keydown',this.keyHandler);this.cy.elements().stop(true,false);this.cy.stop(true,false);this.cy.destroy()}
}
function openFullGraph(scope,selected){
 if(S.graphFull)closeFullGraph();S.graphFull=true;S.graphScope=scope||currentGraphScope();
 const mask=document.createElement('div');mask.id='graph-overlay';mask.innerHTML=`<section class="graph-fullscreen" role="dialog" aria-modal="true" aria-label="完整关系图"><header class="graph-full-header">${b('close-full-graph',icon('back'),'round small soft','aria-label="返回页面"')}<div class="grow"><h2>关联记忆</h2><small>VoiceLog · 比赛日</small></div>${b('graph-focus',icon('search'),'round small','aria-label="聚焦选中节点"')}${b('graph-fit',icon('refresh'),'round small','aria-label="查看全图"')}</header><div class="graph-main"><div class="graph-stage"><div id="full-graph-canvas" class="graph-canvas" tabindex="0" aria-label="可拖动缩放的关系图"></div><div class="graph-tools"><label class="graph-search">${icon('search')}<input id="graph-search" type="search" placeholder="找人物、原话、事情…" aria-label="查找图谱节点"></label>${b('graph-kind','全部','pill active','data-kind="all"')}${b('graph-kind','人物','pill','data-kind="person"')}${b('graph-kind','要点','pill','data-kind="concept"')}${b('graph-sources','原话','pill','id="graph-sources"')}</div><div class="graph-search-results" id="graph-search-results"></div><div class="graph-controls">${b('graph-zoom',icon('plus'),'round','data-factor="1.25" aria-label="放大关系图"')}<span class="zoom-label" id="graph-zoom">100%</span>${b('graph-zoom','−','round','data-factor="0.8" aria-label="缩小关系图"')}${b('graph-fit',icon('refresh'),'round','aria-label="适应全图"')}</div><span class="graph-status" id="graph-status"></span></div><aside class="graph-inspector" id="graph-inspector"></aside></div><footer class="graph-bottom-bar"><div class="graph-type-legend">${['event','source','person','concept','action'].map(t=>`<span><i style="background:${GRAPH_COLORS[t]}"></i>${GRAPH_TYPES[t]}</span>`).join('')}</div>${b('graph-access-list','节点列表','text-button')}</footer></section>`;
 $('#phone').append(mask);[...$('#phone').children].forEach(el=>{if(el!==mask)el.inert=true});document.querySelector('.desktop-note').inert=true;
 fullGraphView=new KnowledgeGraph($('#full-graph-canvas'),S.graphScope,true);if(selected)fullGraphView.select(selected,true);
 $('#graph-search').oninput=e=>{let q=e.target.value.trim();$('#graph-search-results').innerHTML=q?fullGraphView.g.nodes.filter(n=>(n.label+' '+(n.summary||'')).includes(q)).slice(0,8).map(n=>b('graph-select',esc(n.label),'',`data-id="${n.id}"`)).join('')||'<div class="empty">没有找到</div>':''};
 $('#full-graph-canvas').focus({preventScroll:true});
}
function closeFullGraph(){if(fullGraphView){fullGraphView.destroy();fullGraphView=null}$('#graph-overlay')?.remove();S.graphFull=false;[...$('#phone').children].forEach(el=>el.inert=false);document.querySelector('.desktop-note').inert=false;$('#appheader button')?.focus({preventScroll:true})}
