/* Dialogs share one source resolver and keep the underlying scroll position. */
function rememberSheetInputs(){if(!S.sheet)return;S.sheet.inputs={};document.querySelectorAll('#overlays input,#overlays textarea,#overlays select').forEach(el=>{if(el.id)S.sheet.inputs[el.id]=el.type==='checkbox'?el.checked:el.value})}
function setSheetInert(on){for(const id of ['appheader','content','nav']){const el=$('#'+id);if(el)el.inert=on}}
function suspendGraph(){if(!S.graphFull)return;S.graphResume={scope:clone(fullGraphView.scope),selected:fullGraphView.selected,camera:{pan:fullGraphView.cy.pan(),zoom:fullGraphView.cy.zoom()},detail:fullGraphView.detail,kind:fullGraphView.kind,positions:fullGraphView.cy.nodes().map(n=>({id:n.id(),pos:n.position()}))};closeFullGraph()}
function resumeGraph(){const r=S.graphResume;if(!r)return;S.graphResume=null;openFullGraph(r.scope,r.selected);if(r.detail)fullGraphView.toggleSources();if(r.kind&&r.kind!=='all')fullGraphView.filter(r.kind);setTimeout(()=>{if(!fullGraphView)return;fullGraphView.cy.batch(()=>{r.positions.forEach(p=>{const n=fullGraphView.cy.getElementById(p.id);if(n.length)n.position(p.pos)})});fullGraphView.cy.viewport(r.camera)},300)}
function openSheet(kind,props={}){if(S.graphFull)suspendGraph();if(S.sheet){rememberSheetInputs();S.overlayBack.push(clone(S.sheet))}else{returnFocus=document.activeElement;S.overlayBack=[]}S.sheet={kind,...props};renderSheet(true)}
function closeSheet(all=false){if(playingAudio){playingAudio.pause();playingAudio=null}clearTimeout(voiceTimer);S.voice='idle';if(!all&&S.overlayBack.length){S.sheet=S.overlayBack.pop();renderSheet();return}S.sheet=null;S.overlayBack=[];$('#overlays').innerHTML='';setSheetInert(false);if(S.graphResume)resumeGraph();else if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});peopleViewController?.releaseLock()}
function inputRow(label,html){return `<label class="field">${label}${html}</label>`}
function renderSheet(animate=false){
 if(!S.sheet){$('#overlays').innerHTML='';setSheetInert(false);return}
 const sh=S.sheet;let title='',body='',full=false;
  if(sh.kind==='date-picker'){title='选择查看范围';body=`<p class="sub">时间线与人物交汇读取相同的日期状态。</p>${DATA.dates.map((d,i)=>b('date',`10月${d.slice(-2)}日 · ${i===0?'周五 · 比赛日':'周六 · 第二天'}`,S.date===d?'date-option selected':'date-option',`data-date="${d}" aria-pressed="${S.date===d}"`)).join('')}${b('date','10月16–17日 · 多天',S.date==='all'?'date-option selected':'date-option','data-date="all" aria-pressed="'+(S.date==='all')+'"')}`}
  else if(sh.kind==='people-window'){title='选择人物时段';body=`<p class="sub">每个窗口固定两小时，时间轴按真实分钟比例绘制。</p>${[...PEOPLE_WINDOW_LABELS.entries()].map(([start,label])=>b('people-window-set',label,S.peopleWindow?.startMinute===start?'date-option selected':'date-option',`data-start="${start}" aria-pressed="${S.peopleWindow?.startMinute===start}"`)).join('')}`}
  else if(sh.kind==='ics-select'){title='导出已存安排';const saved=DATA.actions.filter(a=>a.status==='saved_demo');body=saved.length?`<p class="sub">每次导出一个 ICS 文件。导出后需自行导入系统日历。</p>${saved.map(a=>`<div class="ics-choice"><div><strong>${esc(a.title)}</strong><small>${dateLabel(a.date)} · ${a.time} · 本机已存</small></div>${b('ics',icon('download')+' 导出','pill dark',`data-id="${a.id}"`)}</div>`).join('')}`:'<div class="empty">目前没有本机已存安排。先确认一项安排，再导出 ICS。</div>'}
  else if(sh.kind==='calendar-more'){title='日历更多操作';body=`${b('policy',icon('settings')+' 自动安排规则','rowlink')}${DATA.actions.some(a=>['cancelled','dismissed'].includes(a.status))?b('action-history','查看撤销与忽略记录','rowlink'):''}<p class="sub">只有明确、有效且本人确认的示例安排会保存到本机。</p>`}
  else if(sh.kind==='action-history'){title='撤销与忽略记录';const history=DATA.actions.filter(a=>['cancelled','dismissed'].includes(a.status));body=history.length?history.map(a=>`<div class="history-action"><div><strong>${esc(a.title)}</strong><small>${dateLabel(a.date)} · ${a.status==='cancelled'?'已撤销':'已忽略'}</small></div>${b('edit-action','重新编辑','pill',`data-id="${a.id}"`)}</div>`).join(''):'<div class="empty">没有撤销或忽略的安排。</div>'}
  else if(sh.kind==='about'){title='声迹 · 离线交互样例';body=`<span class="tag">VoiceLog · UI Demo</span><p class="sub">预置虚构人物与比赛日。设备、转写模型及外部日历未连接。导入音频、页面操作、数据修改与导出在本机运行。</p><div class="toggle-row"><label for="reduce-motion">减少动态效果</label><input type="checkbox" id="reduce-motion" ${store.reduceMotion?'checked':''}></div><div class="section-title">对照视图</div><div class="segmented">${b('ablation','场景分块',S.ablation==='full'?'active':'','data-mode="full"')}${b('ablation','平铺记录',S.ablation==='flat'?'active':'','data-mode="flat"')}</div>${b('export-data',icon('download')+' 导出当前数据','fullbtn secondary')}${b('reset','恢复初始样例','fullbtn danger')}`}
 else if(sh.kind==='ref'){
  title='原话';full=true;const r=C.resolveRef(DATA,sh.id);
  if(!r.ok)body=`<div class="empty">${esc(r.reason)}</div>`;else{const {episode:e,segment:s,ref:rf,stale}=r;let orig=stale?(s.history||[]).find(x=>x.revision===rf.transcriptRevision):s;body=`<div class="path">10.${e.date.slice(-2)} · ${shortTime(e.start)}—${shortTime(e.end)}</div><h3>${esc(eventTitle(e))}</h3><div class="chips-line"><span class="tag blue">${clock(Math.floor(rf.locator.start_ms/1000)).slice(3)}—${clock(Math.floor(rf.locator.end_ms/1000)).slice(3)}</span><span class="tag">${esc(person(s.speaker).name)}</span></div>${audioWidget(e.id)}${stale?'<div class="notice amber">原引用保留旧版本，下方可核对新文字。</div>':''}<div class="transcript-line selected" data-ref-segment="${s.id}"><small>引用版本 v${rf.transcriptRevision}</small>${esc(orig?.text||rf.text||s.text)}</div>${stale?`<div class="transcript-line"><small>当前版本 v${s.revision}</small>${esc(s.text)}</div>`:''}<div class="actions-row">${b('correct',icon('edit')+' 纠正文字','pill',`data-id="${e.id}" data-segment="${s.id}"`)}${s.history?.length?b('history','修订历史','pill',`data-id="${e.id}" data-segment="${s.id}"`):''}</div>${b('source-record','打开完整记录 '+icon('arrow'),'fullbtn secondary',`data-id="${e.id}" data-segment="${s.id}"`)}${b('close-sheet','返回','fullbtn')}`}
 }
 else if(sh.kind==='sound-source'){const e=episode(sh.id);title='声音片段';body=e?`<div class="path">${esc(eventTitle(e))}</div><span class="tag blue">${clock(Math.floor(sh.start/1000)).slice(3)}—${clock(Math.floor(sh.end/1000)).slice(3)}</span>${audioWidget(e.id)}${b('sound-detail','查看本次声音分析','fullbtn secondary',`data-id="${e.id}"`)}`:'<div class="empty">来源不可用</div>'}
 else if(sh.kind==='correct'){title='纠正转写';const e=episode(sh.id),s=e?.segments.find(s=>s.id===sh.segment);body=s?`${inputRow('这句原话',`<textarea id="correction-text" rows="5" maxlength="3000">${esc(s.text)}</textarea>`)}<p class="sub">保留旧版本，相关整理会标为待更新。</p>${b('confirm-correction','保存更正','fullbtn',`data-id="${sh.id}" data-segment="${sh.segment}"`)}`:'<div class="empty">记录不可用</div>'}
 else if(sh.kind==='history'){title='修订历史';const s=episode(sh.id)?.segments.find(s=>s.id===sh.segment);body=s?`<div class="quote"><span class="tag">当前 v${s.revision}</span><p>${esc(s.text)}</p></div>${(s.history||[]).slice().reverse().map(h=>`<div class="card"><span class="tag">v${h.revision}</span><p>${esc(h.text)}</p>${b('restore-transcript','恢复为这段文字','text-button',`data-id="${sh.id}" data-segment="${sh.segment}" data-revision="${h.revision}"`)}</div>`).join('')}`:''}
 else if(sh.kind==='scope'){title='本次使用的资料';let choices=[['all','all','全部可用记录'],...DATA.dates.map(d=>['date',d,'10.'+d.slice(-2)+' · '+(d===DATA.dates[0]?'比赛日':'第二天')]),...DATA.blocks.filter(b=>b.scene==='工作').map(b=>['block',b.id,b.title]),['project','voicelog-day','VoiceLog · 项目'],...DATA.scenes.filter(s=>s.status!=='preview').map(s=>['scene',s.id,s.name]),...DATA.persons.filter(p=>p.id!=='me').map(p=>['person',p.id,'与'+p.name+'的交流']),...DATA.episodes.filter(e=>!e.deleted&&e.segments.length).map(e=>['episode',e.id,eventTitle(e)])];body=`<input type="search" id="scope-search" placeholder="查找场景、人物、记录…" aria-label="搜索资料范围"><div id="scope-choices">${choices.map(([kind,id,name])=>b('set-scope',`${icon(kind==='person'?'user':kind==='episode'?'wave':'layers')}<span class="grow">${esc(name)}</span>${S.scope.kind===kind&&S.scope.id===id?icon('check'):''}`,'rowlink scope-choice',`data-kind="${kind}" data-id="${id}" data-name="${esc(name)}"`)).join('')}</div>`}
 else if(sh.kind==='record'){title=S.record==='syncing'?'正在保存':S.record==='paused'?'已暂停':'录音控制';body=`<div class="record-device"><img src="${PRODUCT}" alt="Work 3200"><div><strong>Work 3200</strong><span class="sub">${S.connected?'演示录音':'连接中断 · 状态待核实'}</span></div></div><div class="record-clock" id="record-clock">${clock(S.recordSeconds)}</div><div class="waveform ${S.record==='recording'?'running':''}" aria-hidden="true">${Array.from({length:31},(_,i)=>`<i style="--h:${12+(Math.sin(i*1.7)+1)*22}px;--d:${i*.03}s"></i>`).join('')}</div><div class="actions-row record-actions">${b('pause-record',icon(S.record==='paused'?'play':'pause')+(S.record==='paused'?' 继续':' 暂停'),'pill',S.record==='syncing'?'disabled':'')}${b('mark-record',icon('tag')+' 重点','pill',S.record!=='recording'?'disabled':'')}${b('stop-record',icon('stop')+' 结束','pill dark',S.record==='syncing'?'disabled':'')}</div><div class="sub" id="record-marks">${S.recordMarks?.length?S.recordMarks.length+' 个重点':''}</div>${inputRow('补记',`<textarea id="record-note" rows="2" placeholder="这段时间想留下什么…">${esc(S.recordNote||'')}</textarea>`)}<div class="sub">本次为控制状态演示，尚未采集音频。</div>`}
 else if(sh.kind==='note'||sh.kind==='dream-note'){title=sh.kind==='dream-note'?'醒后记一段':'补充笔记';body=`<textarea id="note-text" rows="5" maxlength="4000" placeholder="写下想保留的内容…"></textarea>${b('save-note','保存','fullbtn',`data-id="${sh.id||'e11'}"`)}`}
 else if(sh.kind==='policy'){title='自动安排';body=`<span class="tag">本机演示日历</span><div class="toggle-row"><label for="policy-enable">接收明确的本人安排<small>时间明确、来源有效、无冲突。<br>不邀请他人，不改动已有事件。</small></label><input type="checkbox" id="policy-enable" ${store.policy.enabled?'checked':''}></div>${inputRow('本次有效至',`<input id="policy-until" type="date" value="${store.policy.until?.slice(0,10)||'2026-10-17'}">`)}${b('confirm-policy','保存规则','fullbtn')}`}
 else if(sh.kind==='action-edit'){title='编辑安排';const a=DATA.actions.find(a=>a.id===sh.id);body=`${ref(a.sourceRef,'原话')}${inputRow('标题',`<input id="act-title" value="${esc(a.title)}" maxlength="100">`)}<div class="form-grid">${inputRow('日期',`<input id="act-date" type="date" value="${a.date}">`)}${inputRow('时间',`<input id="act-time" type="time" value="${a.time||''}">`)}</div>${inputRow('时长 / 分钟',`<input id="act-duration" type="number" min="5" max="1440" value="${a.duration||30}">`)}${b('update-action','保存草稿','fullbtn',`data-id="${a.id}"`)}`}
 else if(sh.kind==='action-confirm'){title='确认安排';const a=DATA.actions.find(a=>a.id===sh.id),conf=C.conflicts(DATA,a),source=C.resolveRef(DATA,a.sourceRef),check=C.evaluateAction(a,store.policy,{explicitConfirm:true,sourceStale:!source.ok||source.stale,conflict:conf.length>0});body=`<div class="card soft"><h3>${esc(a.title)}</h3><p>${a.date} · ${a.time||'时间待补全'}<br>${a.duration} 分钟 ${esc(a.place||'')}</p>${ref(a.sourceRef,'查看来源')}</div>${conf.length?`<div class="notice amber">与「${esc(conf[0].title)}」时间重叠。</div>`:''}${!source.ok||source.stale?`<div class="notice amber">${esc(source.ok?'来源版本已变化，需要重新核对。':source.reason)}</div>`:''}${!check.allowed?`<div class="notice amber">${esc(check.reason)}</div>${b('edit-action','补充或核对详情','fullbtn',`data-id="${a.id}"`)}`:b('confirm-action','存入本机日历','fullbtn green',`data-id="${a.id}"`)}<div class="sub">保存仅更新本机演示状态，不会写入外部日历。</div>`}
 else if(sh.kind==='voice'){title='语音对话';body=`<span class="tag">示例语音 · 未启用麦克风</span><div class="voice-transcript">${S.voice==='replying'?'明天有联调和颁奖环节。':S.voice==='paused'?'已暂停':'明天有什么安排？'}</div><div class="waveform ${S.voice!=='paused'?'running':''}" aria-hidden="true">${Array.from({length:23},(_,i)=>`<i style="--h:${14+i%5*8}px;--d:${i*.03}s"></i>`).join('')}</div><div class="actions-row">${b('voice-pause',icon(S.voice==='paused'?'play':'pause')+(S.voice==='paused'?' 继续':' 暂停'),'pill')}${b('voice-interrupt','改用文字','pill')}${b('voice-sample',icon('send')+' 发送这句','pill dark')}</div>`}
 else if(sh.kind==='all-people'){title='这段时间的人物';let entries=DATA.encounters.filter(x=>(S.date==='all'||x.start.startsWith(S.date))&&episode(x.episodeId));let ids=[...new Set(entries.map(x=>x.personId))];body=`<input id="people-search" type="search" placeholder="搜索人物…" aria-label="查找人物">${ids.map(id=>{let p=person(id);return `<div class="person-list-row" data-person-search="${esc(p.name)}">${b('person',`${av(id)}<span class="grow"><strong>${esc(p.name)}</strong><small>${esc(p.role)}</small></span>`,'person-list-open',`data-id="${id}"`)}${b('people-pin',S.peoplePin===id?'已固定':'靠近我','pill',`data-id="${id}"`)}</div>`}).join('')}${S.peoplePin?b('people-unpin','取消固定人物','fullbtn secondary'):''}`}
 else if(sh.kind==='encounter'){let e=episode(sh.id),p=person(sh.person);title='这次交汇';body=e?`<div class="person-hero">${av(p.id)}<div><h3>${esc(p.name)}</h3><span class="sub">${minuteText(+sh.start)}—${minuteText(+sh.end)}</span></div></div><div class="card soft"><h3>${esc(eventTitle(e))}</h3><p>${esc(e.items?.[0]||e.summary)}</p>${DATA.refs.filter(r=>r.recordingId===e.id).slice(0,2).map((r,i)=>ref(r.id,two(i+1))).join('')}</div>${b('encounter-record','查看这件事','fullbtn',`data-id="${e.id}"`)}${b('encounter-person','交流与人物','fullbtn secondary',`data-id="${p.id}"`)}`:'<div class="empty">记录不可用</div>'}
 else if(sh.kind==='reply'){const an=(DATA.interpretations||[]).find(a=>a.id===sh.analysis),cand=an?.candidates.find(c=>c.id===sh.candidate),key=an&&cand?replyDraftKey(an,cand):'';title='回复草稿';body=`${inputRow('按你的方式调整',`<textarea id="reply-text" data-reply-key="${esc(key)}" rows="5">${esc(store.replyDrafts?.[key]??cand?.reply??'')}</textarea>`)}${cand?`<div class="chips-line">${cand.refs.map(analysisRef).join('')}</div>`:''}${b('copy-reply',icon('link')+' 复制','fullbtn')}${b('save-reply','留作待回复','fullbtn secondary',`data-person="${an?.personId||S.person}" data-episode="${an?.episodeId||''}" data-reply-key="${esc(key)}"`)}`}
 else if(sh.kind==='person-consent'){title='人物资料';const p=person(S.person);body=`<div class="person-hero">${av(p.id)}<div><h3>${esc(p.name)}</h3><span class="sub">${p.consent==='confirmed_demo'?'已确认的示例身份':'仅本次匿名'}</span></div></div>${b('rename-person','修改显示名称','fullbtn secondary')}${b('anonymize','停止跨日身份关联','fullbtn danger')}`}
 else if(sh.kind==='rename'){title='显示名称';body=`<input id="person-name" value="${esc(person(S.person).name)}" maxlength="50" aria-label="显示名称">${b('save-person-name','保存','fullbtn')}`}
 else if(sh.kind==='memory'){title='我的偏好';body=`<textarea id="memory-text" rows="5" maxlength="2000" aria-label="我的偏好">${esc(store.preference||'先看这一天，需要时再展开细节。')}</textarea>${b('save-memory','保存偏好','fullbtn')}`}
 else if(sh.kind==='mood-edit'){title=sh.id?'当时的感受':'记下此刻';const m=DATA.moods.find(m=>m.id===sh.id),u=store.moodEdits?.[sh.id];body=`${inputRow('一句话形容',`<input id="mood-label" maxlength="40" value="${esc(u?.label|| (m?.basis==='user_report'?m.label:''))}" placeholder="例如：终于有了方向">`)}${inputRow('想补充的话',`<textarea id="mood-note" rows="4" maxlength="1000">${esc(u?.note|| (m?.basis==='user_report'?m.note:''))}</textarea>`)}${inputRow('时间',`<input id="mood-time" type="time" value="${m?.time||'20:30'}">`)}${b('save-mood','保存本人记录','fullbtn',`data-id="${sh.id||''}"`)}`}
 else if(sh.kind==='graph-list'){title='关联节点';body=`<input id="node-list-search" type="search" placeholder="查找节点…" aria-label="搜索节点列表">${graphAllowed(sh.scope||{kind:'all'}).nodes.map(n=>b('list-graph-node',`<span class="node-dot" style="background:${GRAPH_COLORS[n.type]}"></span><span class="grow">${esc(n.label)}</span><small>${GRAPH_TYPES[n.type]}</small>`,'rowlink graph-list-item',`data-id="${n.id}" data-name="${esc(n.label)}"`)).join('')}`}
 else if(sh.kind==='delete-record'){title='删除这条记录？';body=`<p>本机转写、笔记和关联入口将不再显示。外部日历不受影响。</p>${b('confirm-delete-record','删除记录','fullbtn danger',`data-id="${sh.id}"`)}${b('close-sheet','保留','fullbtn secondary')}`}
 else if(sh.kind==='reset'){title='恢复初始样例？';body=`<p>清除当前浏览器中的修改、笔记和演示日历。已导出的文件不受影响。</p>${b('confirm-reset','恢复初始样例','fullbtn danger')}${b('close-sheet','保留当前内容','fullbtn secondary')}`}
 else {title='详情';body='<div class="empty">暂无内容</div>'}
 $('#overlays').innerHTML=`<div class="sheet-mask" data-mask="true"><section class="sheet ${full?'full':''}" role="dialog" aria-modal="true" aria-label="${esc(title)}" tabindex="-1">${full?'':'<div class="handle"></div>'}<div class="sheet-title"><h2>${esc(title)}</h2>${b('close-sheet',icon('close'),'round small soft','aria-label="关闭面板"')}</div><div class="sheet-body">${body}</div></section></div>`;
 setSheetInert(true);for(const [id,value] of Object.entries(sh.inputs||{})){let el=document.getElementById(id);if(el){if(el.type==='checkbox')el.checked=value;else el.value=value}}
 if(animate&&!reduced()){$('#overlays .sheet').animate(full?[{transform:'translateX(25px)',opacity:0},{transform:'translateX(0)',opacity:1}]:[{transform:'translateY(26px)',opacity:0},{transform:'translateY(0)',opacity:1}],{duration:210,easing:'cubic-bezier(.23,1,.32,1)'})}
 wireSheetInputs();requestAnimationFrame(()=>$('#overlays .sheet')?.focus({preventScroll:true}));
}
function wireSheetInputs(){
 const wire=(id,fn)=>{const e=$('#'+id);if(e)e.oninput=fn};
 wire('scope-search',e=>{document.querySelectorAll('.scope-choice').forEach(el=>el.hidden=!el.dataset.name.includes(e.target.value.trim()))});
 wire('people-search',e=>{document.querySelectorAll('[data-person-search]').forEach(el=>el.hidden=!el.dataset.personSearch.includes(e.target.value.trim()))});
 wire('node-list-search',e=>{document.querySelectorAll('.graph-list-item').forEach(el=>el.hidden=!el.dataset.name.includes(e.target.value.trim()))});
 wire('record-note',e=>S.recordNote=e.target.value);
 const reduce=$('#reduce-motion');if(reduce)reduce.onchange=()=>{store.reduceMotion=reduce.checked;persist();document.body.classList.toggle('reduce-motion',reduce.checked)};
 const audio=$('#overlays #bound-audio');if(audio){playingAudio=audio;if(S.sheet.kind==='sound-source'){const from=S.sheet.start/1000,to=S.sheet.end/1000;audio.addEventListener('loadedmetadata',()=>{if(from<audio.duration)audio.currentTime=from;else toast('音频长度不足以定位这个片段。')},{once:true});audio.ontimeupdate=()=>{if(audio.currentTime>=to&&!audio.paused)audio.pause()};}if(S.sheet.kind==='ref'){let r=C.resolveRef(DATA,S.sheet.id);if(r.ok){const from=r.ref.locator.start_ms/1000,to=r.ref.locator.end_ms/1000;const locate=()=>{if(from<audio.duration)audio.currentTime=from;else toast('音频长度不足以定位这段，请核对所选文件。')};if(audio.readyState>=1)locate();else audio.addEventListener('loadedmetadata',locate,{once:true});audio.ontimeupdate=()=>{if(audio.currentTime>=to&&!audio.paused)audio.pause()}}}}
}
