/* Person identity, interval geometry and one-encounter explanation views. */
const PERSON_UI_COLORS={me:'#245E48',lin:'#D3E986',yuan:'#B8CDD0',chen:'#BDD6A8'};
const PEOPLE_PLOT_HEIGHT=336,PEOPLE_WINDOW_MIN=120,PEOPLE_AXIS=44,PEOPLE_RIGHT_GUTTER=28;
const PEOPLE_WINDOWS=[510,540,660,780,900,1020,1140];
const PEOPLE_WINDOW_LABELS=new Map([[510,'08:30–10:30'],[540,'09:00–11:00'],[660,'11:00–13:00'],[780,'13:00–15:00'],[900,'15:00–17:00'],[1020,'17:00–19:00'],[1140,'19:00–21:00']]);
const UI_QUOTE_ANCHORS={'ci-judge':'r-e15-2'};
const ANALYSIS_REF_NUMBERS={'r-e15-2':'01','r-e15-1':'02'};
function peopleView(){
 const day=S.date==='all'?(S.peopleDate||DATA.dates[0]):S.date,w=S.peopleWindow||{startMinute:540,endMinute:660};
 return `<div class="people-shell">${deviceStrip()}${dateControls()}${homeTabs()}<div class="people-window-toolbar"><div class="window-title"><span class="eyebrow">${dateLabel(day)} · 人物交汇</span>${b('people-window-menu',`${minuteText(w.startMinute)}–${minuteText(w.endMinute)} ${icon('down')}`,'window-select')}</div><div class="window-actions">${b('people-window-step','↑','round small soft','data-step="-60" aria-label="向上浏览一小时"')}${b('people-window-step','↓','round small soft','data-step="60" aria-label="向下浏览一小时"')}${b('all-people','全部人物','text-button')}</div></div><div class="people-plot-tools"><div class="people-legend"><span><i class="legend-me"></i>我的记录</span><span><i class="legend-encounter"></i>交流</span></div><span class="people-scroll-hint">上下滑动浏览</span></div><div class="people-chart-card"><div class="people-viewport" id="people-viewport" tabindex="0" aria-label="上下滑动浏览全天人物交汇"><div class="people-axis-head"><div class="people-head-layer" id="people-head-layer"></div></div><div class="people-chart-body" id="people-chart-body" aria-label="人物交流时间轴"></div></div></div><div class="people-live-status" id="people-current" aria-live="polite"></div><div class="people-sort-action">${b('people-stable',S.peopleStable?'固定排列':'随时间靠近','text-button',`aria-pressed="${!!S.peopleStable}"`)}</div><div class="section-title people-list-title">当前时段记录 <span class="sub">短区间可从列表打开</span></div><div class="people-association-list" id="people-association-list"></div></div>`;
}
class PeopleTimeline{
 constructor(){
  this.v=$('#people-viewport');this.body=$('#people-chart-body');this.head=$('#people-head-layer');this.day=S.date==='all'?(S.peopleDate||DATA.dates[0]):S.date;this.start=510;this.end=1260;this.scale=PEOPLE_PLOT_HEIGHT/PEOPLE_WINDOW_MIN;this.visibleStart=Math.max(this.start,Math.min(this.end-PEOPLE_WINDOW_MIN,S.peopleWindow?.startMinute??540));this.visibleEnd=this.visibleStart+PEOPLE_WINDOW_MIN;this.pending=0;this.lock=false;this.lastOrderAt=0;this.dead=false;
  this.entries=DATA.encounters.filter(x=>x.start.startsWith(this.day)&&['confirmed_fixture','session_anonymous'].includes(x.basis)&&episode(x.episodeId));this.ids=[...new Set(this.entries.map(x=>x.personId))];this.order=C.peopleOrder(DATA,this.day,S.focus,S.peopleOrder,!!S.peopleStable,S.peoplePin);this.width=this.v.clientWidth;this.slots=innerWidth<375?2:3;this.laneWidth=(this.width-PEOPLE_AXIS-PEOPLE_RIGHT_GUTTER)/(this.slots+1);this.build();this.v.scrollTop=this.scrollFor(this.visibleStart);this.skipScrollTop=this.v.scrollTop;this.update(Math.max(this.start,Math.min(this.end,S.focus)),true);
  this.onScroll=()=>{if(this.dead||this.pending)return;if(this.skipScrollTop!=null&&Math.abs(this.v.scrollTop-this.skipScrollTop)<1)return;this.skipScrollTop=null;this.pending=requestAnimationFrame(()=>{this.pending=0;this.syncFromScroll()})};
  this.onDown=e=>{if(!e.target.closest('button'))this.lock=true};this.onUp=()=>{if(this.lock)this.releaseLock()};
  this.onKey=e=>{const step={ArrowUp:-5,ArrowDown:5,PageUp:-60,PageDown:60}[e.key];if(step){e.preventDefault();this.seek(S.focus+step)}else if(e.key==='Home'||e.key==='End'){e.preventDefault();this.seek(e.key==='Home'?this.start:this.end)}};
  this.v.addEventListener('scroll',this.onScroll,{passive:true});this.v.addEventListener('pointerdown',this.onDown);this.v.addEventListener('keydown',this.onKey);window.addEventListener('pointerup',this.onUp);window.addEventListener('pointercancel',this.onUp);
  this.onBlur=()=>this.releaseLock();window.addEventListener('blur',this.onBlur);
  this.ro=new ResizeObserver(()=>{if(this.dead||Math.abs(this.width-this.v.clientWidth)<1)return;this.width=this.v.clientWidth;this.slots=innerWidth<375?2:3;this.laneWidth=(this.width-PEOPLE_AXIS-PEOPLE_RIGHT_GUTTER)/(this.slots+1);this.layoutLanes()});this.ro.observe(this.v);
 }
 selfIntervals(){const permitted=DATA.episodes.filter(e=>e.date===this.day&&!e.deleted&&e.public&&e.status!=='preview'&&['audio_fixture','manual_with_audio_fixture'].includes(e.source));return permitted.map(e=>[peopleMinuteOf(e.start),peopleMinuteOf(e.end)]).filter(([a,b])=>b>a)}
 clippedRows(){const base=this.start,end=this.end,rows=[];for(const id of this.ids){const p=person(id),eps=[...new Set(this.entries.filter(x=>x.personId===id).map(x=>x.episodeId))];for(const episodeId of eps){const ep=episode(episodeId);if(!ep)continue;const raw=this.entries.filter(x=>x.personId===id&&x.episodeId===episodeId).map(x=>[peopleMinuteOf(x.start),peopleMinuteOf(x.end)]);for(const [a,b] of C.unionIntervals(raw)){const lo=Math.max(base,a),hi=Math.min(end,b);if(hi<=lo)continue;rows.push({id,episodeId,ep,start:a,end:b,visibleStart:lo,visibleEnd:hi,height:(hi-lo)*this.scale,top:(lo-base)*this.scale})}}}return rows.sort((a,b)=>a.visibleStart-b.visibleStart||a.id.localeCompare(b.id)||a.episodeId.localeCompare(b.episodeId))}
 build(){
   const fullHeight=(this.end-this.start)*this.scale,ticks=[];for(let m=this.start;m<=this.end;m+=30)ticks.push(m);
   const self=C.windowRange(this.selfIntervals(),this.start,this.end,fullHeight);this.body.style.height=(fullHeight+60)+'px';this.body.innerHTML=`${ticks.map(m=>`<div class="people-tick ${m%60===0?'major':''} ${m===this.start?'edge-start':''} ${m===this.end?'edge-end':''}" style="top:${C.windowY(m,this.start,this.end,fullHeight)}px"><time>${minuteText(m)}</time></div>`).join('')}<div class="people-lane me-lane" data-person-lane="me">${self.map(v=>`<div class="self-period" aria-label="本人有样例录音资料的事件上下文 ${minuteText(this.start+v.top/this.scale)}至${minuteText(this.start+(v.top+v.height)/this.scale)}" style="top:${v.top}px;height:${v.height}px"></div>`).join('')}</div>${this.ids.map(id=>`<div class="person-lane" data-person-lane="${id}"></div>`).join('')}`;
  this.head.innerHTML=`<div class="person-head me-head" data-person-head="me">${av('me')}<span class="person-label">我</span></div>`;
  for(const id of this.ids){const p=person(id);this.head.insertAdjacentHTML('beforeend',`<button type="button" class="person-head" data-person-head="${id}" data-act="person" data-id="${id}" aria-label="查看${esc(p.name)}">${av(id)}<span class="person-label" title="${esc(p.name)}">${esc(p.name)}</span></button>`)}
   for(const row of this.clippedRows()){const color=PERSON_UI_COLORS[row.id]||palePersonColor(person(row.id).color);const h=row.height,kind=h<22?'micro':h<44?'short':h<88?'compact':'full';this.body.insertAdjacentHTML('beforeend',`<button type="button" class="enc-card ${kind}" data-act="encounter" data-person="${row.id}" data-id="${row.episodeId}" data-start="${row.start}" data-end="${row.end}" aria-label="${esc(person(row.id).name)}，${minuteText(row.start)}至${minuteText(row.end)}，${esc(eventTitle(row.ep))}" style="top:${row.top}px;height:${row.height}px;--person-color:${color}">${h>=88?`<time class="enc-time-stack"><span>${minuteText(row.visibleStart)}</span><span>${minuteText(row.visibleEnd)}</span></time><span class="enc-title">${esc(row.ep.laneLabel||eventTitle(row.ep))}</span>`:h>=44?`<span class="enc-title">${esc(row.ep.laneLabel||eventTitle(row.ep))}</span>`:h>=22?`<span class="short-initial">${esc(person(row.id).initial)}</span>`:''}</button>`)}
   this.renderVisibleList();this.layoutLanes();
  }
  renderVisibleList(){const rows=this.clippedRows().filter(x=>x.start<this.visibleEnd&&x.end>this.visibleStart),ownKeys=new Set(this.selfIntervals().filter(([a,b])=>a<this.visibleEnd&&b>this.visibleStart).map(([a])=>this.ownEpisodeAt(Math.max(a,this.visibleStart))));this.renderAssociationList(rows,[...ownKeys])}
  ownEpisodeAt(minute){const e=DATA.episodes.filter(e=>e.date===this.day&&!e.deleted&&e.public&&e.status!=='preview'&&['audio_fixture','manual_with_audio_fixture'].includes(e.source)&&minute>=peopleMinuteOf(e.start)&&minute<peopleMinuteOf(e.end)).sort((a,b)=>a.id.localeCompare(b.id))[0];return e?.id||DATA.episodes.find(e=>e.date===this.day&&e.source==='audio_fixture')?.id||'e02'}
  renderAssociationList(rows,ownKeys=[]){const own=DATA.episodes.filter(e=>ownKeys.includes(e.id)).map(e=>`<button type="button" class="association-row own-row" data-act="episode" data-id="${e.id}"><span class="association-time">${shortTime(e.start)}–${shortTime(e.end)}</span><span class="grow"><strong>我的记录时段</strong><small>${esc(eventTitle(e))}</small></span>${icon('chevron')}</button>`);const people=rows.map(x=>`<button type="button" class="association-row" data-act="encounter" data-person="${x.id}" data-id="${x.episodeId}" data-start="${x.start}" data-end="${x.end}"><span class="association-avatar" style="--person-color:${PERSON_UI_COLORS[x.id]||palePersonColor(person(x.id).color)}">${esc(person(x.id).initial)}</span><span class="grow"><strong>${esc(person(x.id).name)} · ${esc(x.ep.laneLabel||eventTitle(x.ep))}</strong><small>${minuteText(x.start)}–${minuteText(x.end)}${x.start<this.visibleStart||x.end>this.visibleEnd?' · 区间跨窗':''}</small></span>${icon('chevron')}</button>`);$('#people-association-list').innerHTML=own.concat(people).join('')||'<div class="empty">这个时段没有已记录的人物交汇</div>'}
 layoutLanes(){const axis=PEOPLE_AXIS,laneWidth=(this.width-axis-PEOPLE_RIGHT_GUTTER)/(this.slots+1);this.laneWidth=laneWidth;const me=this.v.querySelector('[data-person-lane="me"]');if(me){me.style.left='0px';me.style.width=laneWidth+'px';me.style.transform=`translateX(${axis}px)`;me.style.setProperty('--me-lane-mid',`${laneWidth/2}px`);me.style.setProperty('--me-lane-width',`${laneWidth}px`)}const ordered=this.order.filter(id=>this.ids.includes(id));this.ids.filter(id=>!ordered.includes(id)).forEach(id=>ordered.push(id));ordered.forEach((id,i)=>{const x=axis+(i+1)*laneWidth,visible=i<this.slots,head=this.head.querySelector(`[data-person-head="${id}"]`),lane=this.v.querySelector(`[data-person-lane="${id}"]`);for(const el of [head,lane])if(el){el.style.width=laneWidth+'px';el.style.transform=`translateX(${x}px)`;el.classList.toggle('inactive',!visible);el.setAttribute('aria-hidden',visible?'false':'true');if(el.tagName==='BUTTON')el.tabIndex=visible?0:-1;el.querySelectorAll('button').forEach(btn=>btn.tabIndex=visible?0:-1)} });this.v.querySelectorAll('.enc-card').forEach(el=>{const id=el.dataset.person,i=ordered.indexOf(id);el.style.left=`${axis+(i+1)*laneWidth+4}px`;el.style.width=`${Math.max(2,laneWidth-8)}px`;el.classList.toggle('inactive',i>=this.slots)});const headMe=this.head.querySelector('[data-person-head="me"]');if(headMe){headMe.style.left=`${axis}px`;headMe.style.width=laneWidth+'px'} }
 update(min,force=false){
  S.focus=Math.max(this.start,Math.min(this.end,min));
  const active=new Set(this.entries.filter(x=>S.focus>=peopleMinuteOf(x.start)&&S.focus<peopleMinuteOf(x.end)).map(x=>x.personId));let next=C.peopleOrder(DATA,this.day,S.focus,this.order,S.peopleStable||reduced(),S.peoplePin);if(this.lock||S.sheet)next=this.order;const changed=next.join()!==this.order.join(),remaining=270-(performance.now()-this.lastOrderAt);if(changed&&remaining>0&&!force){clearTimeout(this.reorderTimer);this.reorderTimer=setTimeout(()=>{this.reorderTimer=null;this.update(S.focus,true)},remaining);next=this.order}else if(changed){clearTimeout(this.reorderTimer);this.reorderTimer=null;this.lastOrderAt=performance.now()}this.order=next;S.peopleOrder=next;this.layoutLanes();this.v.querySelectorAll('.enc-card').forEach(el=>el.classList.toggle('active',S.focus>=+el.dataset.start&&S.focus<+el.dataset.end));const current=$('#people-current');if(current)current.innerHTML=active.size?`<span>${minuteText(S.focus)} · 正在交流</span><strong>${[...active].slice(0,3).map(id=>esc(person(id).name)).join('、')}${active.size>3?'等':''}</strong>`:`<span>${minuteText(S.focus)} · 当前没有已记录交流</span>`;
 }
  scrollFor(minute){return this.head.parentElement.offsetHeight+(minute-this.start)*this.scale}
  syncFromScroll(){const start=Math.max(this.start,Math.min(this.end-PEOPLE_WINDOW_MIN,Math.round((this.start+Math.max(0,this.v.scrollTop-this.head.parentElement.offsetHeight)/this.scale)/5)*5));if(start!==this.visibleStart){this.visibleStart=start;this.visibleEnd=start+PEOPLE_WINDOW_MIN;S.peopleWindow={startMinute:start,endMinute:this.visibleEnd};const button=$('.window-select');if(button)button.innerHTML=`${minuteText(start)}–${minuteText(this.visibleEnd)} ${icon('down')}`;this.renderVisibleList()}this.update(Math.min(this.end,start+Math.round(PEOPLE_WINDOW_MIN/2)))}
  setWindow(start,sortOnRelease=true){const clamped=Math.max(this.start,Math.min(this.end-PEOPLE_WINDOW_MIN,Math.round(start/5)*5)),delta=clamped-this.visibleStart;this.visibleStart=clamped;this.visibleEnd=clamped+PEOPLE_WINDOW_MIN;S.peopleWindow={startMinute:clamped,endMinute:this.visibleEnd};const button=$('.window-select');if(button)button.innerHTML=`${minuteText(clamped)}–${minuteText(this.visibleEnd)} ${icon('down')}`;this.v.scrollTop=this.scrollFor(clamped);this.skipScrollTop=this.v.scrollTop;this.renderVisibleList();this.update(Math.max(clamped,Math.min(this.visibleEnd,S.focus+delta)),!sortOnRelease)}
  stepWindow(delta){this.lock=true;this.setWindow(this.visibleStart+delta,false);this.releaseLock()}
  selectWindow(start){this.lock=true;this.setWindow(start,false);this.releaseLock()}
  releaseLock(){if(this.dead)return;this.lock=false;this.update(S.focus,true)}
  seek(min){const target=Math.max(this.start,Math.min(this.end,+min));if(target<this.visibleStart||target>this.visibleEnd)this.setWindow(target-PEOPLE_WINDOW_MIN/2);this.update(target)}
  destroy(){this.dead=true;if(this.pending)cancelAnimationFrame(this.pending);clearTimeout(this.reorderTimer);this.v.removeEventListener('scroll',this.onScroll);this.v.removeEventListener('pointerdown',this.onDown);this.v.removeEventListener('keydown',this.onKey);window.removeEventListener('pointerup',this.onUp);window.removeEventListener('pointercancel',this.onUp);window.removeEventListener('blur',this.onBlur);this.ro?.disconnect()}
}
function peopleMinuteOf(stamp){return +stamp.slice(11,13)*60+ +stamp.slice(14,16)}
function palePersonColor(color){const hex=color?.replace('#','')||'7b8973';if(hex.length!==6)return '#C8D6C9';const n=parseInt(hex,16),r=n>>16,g=(n>>8)&255,b=n&255;return `#${[r,g,b].map(v=>Math.round(v*.34+255*.66).toString(16).padStart(2,'0')).join('')}`}
function analysisForPerson(id){const explicit=(DATA.interpretations||[]).find(x=>x.id===S.analysisId&&x.personId===id);return explicit||(DATA.interpretations||[]).find(x=>x.personId===id)}
function candidateState(id){return store.candidateChoices?.[id]||null}
function analysisAnchor(an){return UI_QUOTE_ANCHORS[an.id]||an.quoteRef}
function analysisRef(id){const resolved=C.resolveRef(DATA,id,{kind:'all'});if(!resolved.ok)return `<span class="source-unavailable">来源不可用：${esc(resolved.reason)}</span>`;const r=resolved.ref.locator,stamp=n=>`${two(Math.floor(n/60000))}:${two(Math.floor(n/1000)%60)}`;return `<span class="analysis-reference">${ref(id,ANALYSIS_REF_NUMBERS[id]||'原话')}<time>${stamp(r.start_ms)}–${stamp(r.end_ms)}</time></span>`}
function candidateMarkup(an,c,index){const selected=candidateState(an.id)===c.id,rejected=(store.rejectedCandidates||[]).includes(an.id+':'+c.id),refs=c.refs.map(analysisRef).join(' '),choice=b('select-candidate',selected?'已选择':'选择此理解',`candidate-choice ${selected?'selected':''}`,`data-analysis="${an.id}" data-id="${c.id}" aria-pressed="${selected}"`),reject=b('reject-candidate',rejected?'撤销否定':'不符合','text-button',`data-analysis="${an.id}" data-id="${c.id}" aria-pressed="${rejected}"`),content=`<p>${esc(c.reason)}</p><div class="candidate-refs">${refs}</div><div class="actions-row">${choice}${reject}</div>${rejected?'<p class="sub">已标记不符合 · 不采纳此解释</p>':''}`;if(c.support==='依据不足')return `<details class="candidate-card insufficient-card" data-candidate="${c.id}"><summary><span><span class="tag amber">依据不足</span><strong>${esc(c.label)}</strong></span>${icon('chevron')}</summary><div class="candidate-content">${content}</div></details>`;return `<article class="candidate-card ${index===0?'candidate-feature':''}" data-candidate="${c.id}"><div class="candidate-head"><div><span class="tag ${index===0?'support-tag':''}">${esc(c.support||'可继续核对')}</span><strong>${esc(c.label)}</strong></div>${selected?`<span class="selection-check" aria-label="已选择">${icon('check')}</span>`:''}</div><div class="candidate-content">${content}</div></article>`}
function replyDraftKey(an,candidate){return `${an.id}:${candidate.id}`}
function analysisUnderstanding(an,ep){const anchor=analysisAnchor(an),resolved=C.resolveRef(DATA,anchor,{kind:'episode',id:ep.id}),quote=resolved.ok?resolved.segment.text:'当前来源不可用';const selected=candidateState(an.id),replyCandidate=an.candidates.find(c=>c.id===selected)||an.candidates[0],key=replyDraftKey(an,replyCandidate),draft=store.replyDrafts?.[key]??replyCandidate.reply??'';return `<section class="analysis-quote-card"><div class="analysis-card-title"><span class="tileicon">${icon('chat')}</span><h3>他说了什么</h3></div><blockquote>${esc(quote)}</blockquote><div class="quote-meta">${analysisRef(anchor)}${!resolved.ok?`<span>${esc(resolved.reason)}</span>`:''}</div></section><h3 class="section-title analysis-section-title">可能的理解</h3>${an.candidates.map((c,i)=>candidateMarkup(an,c,i)).join('')}<section class="reply-card"><div class="reply-card-head"><span class="tileicon">${icon('edit')}</span><div><h3>回复草稿</h3><p>按${esc(replyCandidate.label)}整理 · 只复制，不会自动发送</p></div></div><textarea id="person-reply-text" data-reply-key="${esc(key)}" rows="4" aria-label="编辑回复草稿">${esc(draft)}</textarea><div class="actions-row">${b('copy-person-reply',icon('link')+' 复制回复','pill green')}${b('save-person-reply','留作待回复','pill')}</div></section>`}
function analysisOriginals(an,ep){const refs=DATA.refs.filter(r=>r.recordingId===ep.id).sort((a,b)=>a.locator.start_ms-b.locator.start_ms);return `<div class="path">${dateLabel(ep.date)} · ${shortTime(ep.start)}–${shortTime(ep.end)} · 本次交流的原话</div>${audioWidget(ep.id)}${ep.segments.slice().sort((a,b)=>a.start_ms-b.start_ms).map((s,i)=>{const rs=refs.filter(r=>r.segmentId===s.id);return `<article class="transcript-line" data-segment="${s.id}"><small>${esc(person(s.speaker).name)} · ${two(Math.floor(s.start_ms/60000))}:${two(Math.floor(s.start_ms/1000)%60)}${s.revision>1?' · v'+s.revision:''}</small>${esc(s.text)}<div class="transcript-refs">${rs.map(r=>analysisRef(r.id)).join('')}</div></article>`}).join('')}${(DATA.interpretations||[]).filter(x=>x.personId===an.personId&&x.id!==an.id).map(other=>`<section class="calendar-secondary"><h3>其他一次交流</h3>${b('analysis-select',`${esc(other.title)} · ${dateLabel(DATA.episodes.find(e=>e.id===other.episodeId)?.date||ep.date)}`,'rowlink',`data-id="${other.id}"`)}</section>`).join('')}</div>`}
function personPage(){
 const p=person(S.person),an=analysisForPerson(S.person),ep=an?episode(an.episodeId):null,personEpisodes=DATA.episodes.filter(e=>!e.deleted&&e.participants.includes(S.person)&&(S.date==='all'||e.date===S.date));const tabs=['理解','原话','关联'];const tabbar=`<div class="person-tabs" role="tablist" aria-label="人物交流页面">${tabs.map(t=>b('person-tab',t,S.personTab===t?'active':'',`data-tab="${t}" role="tab" aria-selected="${S.personTab===t}"`)).join('')}</div>`;
 const time=ep?`${dateLabel(ep.date)} ${shortTime(ep.start)}–${shortTime(ep.end)}`:'';const hero=an&&ep?`<section class="encounter-hero">${av(p.id)}<div class="grow"><h2>${esc(p.name)}</h2><p>${p.consent==='session_only'?'本次匿名':'已确认示例身份'} · ${time}</p></div></section>`:`<section class="encounter-hero">${av(p.id)}<div class="grow"><h2>${esc(p.name)}</h2><p>${esc(p.role)}</p></div></section>`;
 let body='';if(S.personTab==='关联')body=relationView({kind:'person',id:S.person});else if(S.personTab==='原话')body=an&&ep?analysisOriginals(an,ep):personEpisodes.filter(e=>e.segments.length).map(e=>`<section class="person-history-card"><h3>${esc(eventTitle(e))}</h3><p class="sub">${dateLabel(e.date)} · ${shortTime(e.start)}–${shortTime(e.end)}</p>${e.segments.map(s=>`<div class="transcript-line"><small>${esc(person(s.speaker).name)}</small>${esc(s.text)}${ref(`r-${e.id}-${e.segments.indexOf(s)+1}`,'原话')}</div>`).join('')}</section>`).join('')||'<div class="empty">暂时没有可打开的原话。</div>';else body=an&&ep?analysisUnderstanding(an,ep):`${personEpisodes.length?`<div class="section-title">相关记录</div>${personEpisodes.map(recordRow).join('')}`:'<div class="empty">暂时没有这次交流的候选理解。</div>'}`;
 return `<div class="person-page">${hero}${tabbar}${body}${S.personTab!=='关联'?`${b('ask-person',icon('chat')+' 围绕这次交流提问','fullbtn secondary')}${b('person-graph',icon('link')+' 查看关联','fullbtn')}`:''}</div>`;
}
function moodPage(){let points=(DATA.moods||[]).filter(m=>(S.date==='all'||m.date===S.date)&&!(store.dismissedMoods||[]).includes(m.id));return `<div class="path">${S.date==='all'?'10.16—10.17':'10.'+S.date.slice(-2)}</div><div class="title-row"><h2>心情历程</h2>${b('mood-new',icon('plus'),'round small','aria-label="记录此刻感受"')}</div><div class="legend"><span><i style="background:#245e48"></i>本人记录</span><span><i style="background:#c6e46b"></i>待核对线索</span></div><div class="mood-list" style="margin-top:24px">${points.map(m=>{const u=store.moodEdits?.[m.id],label=u?.label||m.label,basis=u?'user_report':m.basis;return `<article class="mood-point"><div class="top"><time>${m.time}</time><h3>${esc(label)}</h3></div><div class="tag ${basis==='candidate'?'amber':''}" style="margin-top:8px">${basis==='candidate'?'交流中的候选线索':'本人记录'}</div><p>${esc(u?.note||m.note)} ${basis==='candidate'&&m.ref?ref(m.ref,'原话'):''}</p><div class="actions-row">${b('mood-edit',basis==='candidate'?'说说当时的感受':'修改记录','text-button',`data-id="${m.id}"`)}${basis==='candidate'?b('mood-dismiss','不符合','text-button',`data-id="${m.id}"`):''}</div></article>`}).join('')||'<div class="empty">这一天还没有心情记录</div>'}</div>${b('mood-new',icon('plus')+' 记一下现在','fullbtn secondary')}`}
